export const MOCK_CERTIFICATIONS = [
  {
    id: 'cert-1',
    name: 'Jaivik Bharat / NPOP Organic',
    type: 'NATIONAL',
    country: 'India',
    issuingAuthority: 'APEDA Ministry of Commerce & Industry',
    licenseNo: 'NPOP/NAB/0014/2025',
    verifiedScore: 99,
    validUntil: '2028-12-31',
    badgeText: 'National Organic Standard',
    logo: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-2',
    name: 'USDA Organic NOP Certified',
    type: 'INTERNATIONAL',
    country: 'United States / Global',
    issuingAuthority: 'USDA National Organic Program',
    licenseNo: 'USDA-NOP-884920-US',
    verifiedScore: 98,
    validUntil: '2027-09-30',
    badgeText: 'USDA Global Organic Standard',
    logo: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-3',
    name: 'Maharashtra State Organic Board Seal',
    type: 'LOCAL_GOV',
    country: 'India (Maharashtra State)',
    issuingAuthority: 'State Department of Agriculture & Agro-Board',
    licenseNo: 'MH-AGRI-ORG-4402',
    verifiedScore: 96,
    validUntil: '2026-11-15',
    badgeText: 'Local Govt Approved',
    logo: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-4',
    name: 'CCOF Local Regional Authority Seal',
    type: 'LOCAL_GOV',
    country: 'United States (California)',
    issuingAuthority: 'California Dept of Food & Agriculture (CDFA)',
    licenseNo: 'CDFA-CCOF-77189-CA',
    verifiedScore: 97,
    validUntil: '2027-04-20',
    badgeText: 'Local State Approved',
    logo: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=100&auto=format&fit=crop&q=80',
  },
];

export const MOCK_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Bio-Active NPK Liquid Organic Fertilizer',
    category: 'fertilizers',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Fertilizer Manufacturer',
    origin: 'Gujarat, India',
    rating: 4.9,
    reviewsCount: 142,
    certifiedType: 'NATIONAL',
    certName: 'Jaivik Bharat & USDA Organic',
    certLicense: 'NPOP/NAB/0014/2025',
    labPurityRating: '99.4% Chemical-Free',
    image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?w=600&auto=format&fit=crop&q=80',
    
    // Retail Pricing
    retailPrice: 450,
    retailUnit: 'Liter',
    retailMinQty: 1,
    
    // Bulk Pricing
    bulkAvailable: true,
    bulkPricePerTon: 85000,
    bulkMinTons: 2,
    bulkUnit: 'Ton',
    
    description: 'High-potency microbial nitrogen, phosphorus, and potassium liquid fertilizer. Enhances root mass by 40% and boosts soil organic carbon naturally.',
    npkRatio: 'N: 6% | P: 4% | K: 8%',
    usageDose: '5 ml per liter of irrigation water or 200 Liters per acre via drip.',
    inStock: true,
  },
  {
    id: 'prod-2',
    name: 'Direct Farm Harvest: 100% Organic Sharbati Wheat',
    category: 'bulkHarvest',
    sellerName: 'Swadesh Agro-Cooperative Farmer Collective',
    sellerType: 'Certified Organic Farmer Collective',
    origin: 'Madhya Pradesh, India',
    rating: 4.95,
    reviewsCount: 88,
    certifiedType: 'LOCAL_GOV',
    certName: 'MP State Agro Organic Board & Jaivik Bharat',
    certLicense: 'MH-AGRI-ORG-4402',
    labPurityRating: '100% Pesticide-Residue Free',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80',
    
    // Retail Pricing
    retailPrice: 65,
    retailUnit: 'Kg',
    retailMinQty: 5,
    
    // Bulk Pricing
    bulkAvailable: true,
    bulkPricePerTon: 42000,
    bulkMinTons: 5,
    bulkUnit: 'Ton',
    
    description: 'Premium golden Sharbati wheat grown without synthetic pesticides or chemical fertilizers. Direct farm shipment to flour mills, food processors, and bulk buyers.',
    moistureContent: '11.5% Max',
    grainPurity: '99.8%',
    inStock: true,
  },
  {
    id: 'prod-3',
    name: 'Neem-Shield Bio-Pesticide & Cold-Pressed Neem Oil',
    category: 'bioPesticides',
    sellerName: 'NeemTech Organics Ltd.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Rajasthan, India',
    rating: 4.8,
    reviewsCount: 96,
    certifiedType: 'NATIONAL',
    certName: 'USDA NOP & EU Bio Standards',
    certLicense: 'USDA-NOP-884920-US',
    labPurityRating: '10,000 PPM Azadirachtin',
    image: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=600&auto=format&fit=crop&q=80',
    
    retailPrice: 380,
    retailUnit: '500ml Bottle',
    retailMinQty: 1,
    
    bulkAvailable: true,
    bulkPricePerTon: 110000,
    bulkMinTons: 1,
    bulkUnit: 'Ton (Barrel Pack)',
    
    description: 'Broad-spectrum botanical pesticide effective against caterpillars, aphids, thrips, and whiteflies. Safe for beneficial pollinators like bees.',
    inStock: true,
  },
  {
    id: 'prod-4',
    name: 'Premium Vermicompost Soil Conditioner (Enriched with Humic Acid)',
    category: 'fertilizers',
    sellerName: 'EarthWorm Gold Farmers Union',
    sellerType: 'Local Farmer Cooperative',
    origin: 'Punjab, India',
    rating: 4.7,
    reviewsCount: 210,
    certifiedType: 'LOCAL_GOV',
    certName: 'Punjab State Organic Agriculture Council',
    certLicense: 'PB-AGRI-ORG-1029',
    labPurityRating: '100% Pure Worm Castings',
    image: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?w=600&auto=format&fit=crop&q=80',
    
    retailPrice: 25,
    retailUnit: 'Kg Bag',
    retailMinQty: 5,
    
    bulkAvailable: true,
    bulkPricePerTon: 12500,
    bulkMinTons: 3,
    bulkUnit: 'Ton',
    
    description: 'Rich dark humus created by Eisenia Fetida earthworms. Loaded with beneficial mycorrhizae, micronutrients, and humic substances for soil rejuvenation.',
    inStock: true,
  },
  {
    id: 'prod-5',
    name: 'High-Yield Hybrid Organic Tomato Seeds (F1 Disease Resistant)',
    category: 'seeds',
    sellerName: 'Vedic Seed Innovations',
    sellerType: 'Seed Nursery & Breeder',
    origin: 'Karnataka, India',
    rating: 4.9,
    reviewsCount: 175,
    certifiedType: 'NATIONAL',
    certName: 'National Seed Certification Board',
    certLicense: 'NSCB-IND-99120',
    labPurityRating: '98% Germination Guaranteed',
    image: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&auto=format&fit=crop&q=80',
    
    retailPrice: 220,
    retailUnit: '10g Packet',
    retailMinQty: 1,
    
    bulkAvailable: false,
    description: 'High-yielding semi-determinate tomato seeds bred for wilt resistance and intense flavor. Suitable for open field and greenhouse cultivation.',
    inStock: true,
  },
  {
    id: 'prod-6',
    name: 'Solar-Powered Automated Drip Irrigation Kit (1 Acre)',
    category: 'equipment',
    sellerName: 'SunAgro Tech Systems',
    sellerType: 'Equipment Supplier',
    origin: 'Maharashtra, India',
    rating: 4.85,
    reviewsCount: 54,
    certifiedType: 'NATIONAL',
    certName: 'Bureau of Indian Standards (BIS Certified)',
    certLicense: 'BIS-AGRI-44120',
    labPurityRating: 'ISO 9001:2025 Quality Passed',
    image: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=600&auto=format&fit=crop&q=80',
    
    retailPrice: 24500,
    retailUnit: 'Full Kit (1 Acre)',
    retailMinQty: 1,
    
    bulkAvailable: true,
    bulkPricePerTon: 215000,
    bulkMinTons: 1,
    bulkUnit: 'Set of 10 Acres',
    
    description: 'Complete water-saving precision drip irrigation system with automatic solar timer pump. Reduces water usage by up to 60%.',
    inStock: true,
  },
];

export const MOCK_COMMODITY_PRICES = [
  { crop: 'Organic Wheat (MP Sharbati)', priceRetail: '₹65 / Kg', priceBulk: '₹42,000 / Ton', change: '+2.4%', trend: 'up' },
  { crop: 'Bio-NPK Liquid Fertilizer', priceRetail: '₹450 / Liter', priceBulk: '₹85,000 / Ton', change: '-0.8%', trend: 'down' },
  { crop: 'Organic Basmati Paddy Rice', priceRetail: '₹95 / Kg', priceBulk: '₹72,000 / Ton', change: '+3.1%', trend: 'up' },
  { crop: 'Cold-Pressed Neem Oil', priceRetail: '₹380 / 500ml', priceBulk: '₹110,000 / Ton', change: '0.0%', trend: 'stable' },
  { crop: 'Organic Vermicompost', priceRetail: '₹25 / Kg', priceBulk: '₹12,500 / Ton', change: '+1.5%', trend: 'up' },
];

export const MOCK_SHIPMENTS = [
  {
    id: 'SHIP-8921',
    type: 'BULK_FREIGHT',
    title: '15 Tons Organic Sharbati Wheat Truckload',
    origin: 'Farm #4, Indore, MP',
    destination: 'AgroProcessor Flour Mill Warehouse, Pune, MH',
    weight: '15.0 Tons',
    carrier: 'EcoFreight Heavy Trucking Direct',
    status: 'IN_TRANSIT',
    driverName: 'Ramesh Singh',
    driverPhone: '+91 98230 11200',
    vehicleNo: 'MH-12-VT-9921',
    estDelivery: 'Tomorrow, 04:30 PM',
    escrowStatus: '₹6,30,000 Held in Escrow (Release after destination lab check)',
    milestones: [
      { label: 'Harvest Loaded at Farm', date: '24 Jul, 08:00 AM', completed: true },
      { label: 'Weighbridge & Initial Quality Stamp', date: '24 Jul, 11:30 AM', completed: true },
      { label: 'En-Route on Highway NH-52', date: '24 Jul, 04:00 PM', completed: true },
      { label: 'Destination Lab Check at Warehouse', date: '25 Jul, 02:00 PM', completed: false },
      { label: 'Final Escrow Release to Farmer', date: '25 Jul, 05:00 PM', completed: false },
    ],
  },
  {
    id: 'SHIP-4402',
    type: 'RETAIL_PARCEL',
    title: '5 Liters Bio-NPK Liquid & 2 Kg Neem Powder',
    origin: 'GreenBio Earth Depot, Ahmedabad, GJ',
    destination: 'Green Acres Home Farm, Jaipur, RJ',
    weight: '7.2 Kg',
    carrier: 'GreenParcel Carbon-Neutral Courier',
    status: 'DISPATCHED',
    trackingNo: 'GP-992018442-IN',
    estDelivery: '26 Jul, 02:00 PM',
    escrowStatus: 'Payment Completed via UPI',
    milestones: [
      { label: 'Order Confirmed', date: '23 Jul, 02:15 PM', completed: true },
      { label: 'Lab Sealed & Packaged', date: '24 Jul, 09:00 AM', completed: true },
      { label: 'Dispatched via GreenParcel Express', date: '24 Jul, 01:00 PM', completed: true },
      { label: 'Out for Last-Mile Delivery', date: '26 Jul, 09:00 AM', completed: false },
    ],
  },
];

export const MOCK_COMMUNITY_POSTS = [
  {
    id: 'post-1',
    author: 'Dr. Anita Deshmukh',
    role: 'Agri-Expert & Soil Microbiologist',
    verifiedExpert: true,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    title: 'How to transition 5 acres from chemical farming to 100% Certified Organic without yield drop',
    content: 'Transitioning requires a 3-phase soil rejuvenation strategy. Start with bio-char and vermicompost to reseed beneficial mycorrhizae bacteria before cutting synthetic nitrogen...',
    tags: ['Soil Health', 'Organic Transition', 'Bio-Fertilizers'],
    upvotes: 246,
    repliesCount: 38,
    date: '2 hours ago',
  },
  {
    id: 'post-2',
    author: 'Gurpreet Singh',
    role: 'Organic Wheat Farmer (20 Tons Harvest)',
    verifiedExpert: false,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    title: 'Direct Bulk Sales Experience: Bypassing Mandi Middlemen for 18 Tons of Wheat',
    content: 'Used Eco Swadesh Direct Freight last week to supply 18 Tons of organic wheat directly to a Pune flour mill. Escrow payment was released within 2 hours of lab test at warehouse!',
    tags: ['Direct Bulk Trade', 'Zero Middlemen', 'Escrow Payment'],
    upvotes: 189,
    repliesCount: 24,
    date: '5 hours ago',
  },
];

export const MOCK_AI_DIAGNOSES = [
  {
    id: 'diag-1',
    cropName: 'Tomato Plant (Solanum lycopersicum)',
    detectedDisease: 'Early Blight (Alternaria solani)',
    confidence: '96.8% Accuracy',
    severity: 'Moderate Infection',
    organicCure: [
      'Spray 5ml/L Cold-Pressed Neem Oil (10,000 PPM) every 5 days.',
      'Apply Trichoderma viride bio-fungicide to soil near root zone.',
      'Remove lower infected yellow leaves and maintain proper spacing for airflow.',
    ],
    recommendedFertilizer: 'Bio-Active Potassium & Seaweed Extract for immunity boost.',
  },
];
