export const MOCK_CERTIFICATIONS = [
  {
    id: 'cert-1',
    name: 'Jaivik Bharat / NPOP Organic',
    type: 'NATIONAL',
    country: 'India',
    issuingAuthority: 'APEDA Ministry of Commerce & Industry',
    licenseNo: 'NPOP/NAB/0014/2025',
    verifiedScore: 99,
    validUntil: '2028-12-31',
    badgeText: 'National Organic Standard',
    logo: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-2',
    name: 'USDA Organic NOP Certified',
    type: 'INTERNATIONAL',
    country: 'United States / Global',
    issuingAuthority: 'USDA National Organic Program',
    licenseNo: 'USDA-NOP-884920-US',
    verifiedScore: 98,
    validUntil: '2027-09-30',
    badgeText: 'USDA Global Organic Standard',
    logo: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-3',
    name: 'Maharashtra State Organic Board Seal',
    type: 'LOCAL_GOV',
    country: 'India (Maharashtra State)',
    issuingAuthority: 'State Department of Agriculture & Agro-Board',
    licenseNo: 'MH-AGRI-ORG-4402',
    verifiedScore: 96,
    validUntil: '2026-11-15',
    badgeText: 'Local Govt Approved',
    logo: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-4',
    name: 'PGS-India Green (Conversion Phase)',
    type: 'NATIONAL',
    country: 'India',
    issuingAuthority: 'National Centre of Organic Farming (NCOF / MoA&FW)',
    licenseNo: 'PGS-INDIA-GRN-2025-091',
    verifiedScore: 95,
    validUntil: '2027-03-31',
    badgeText: 'PGS-India Green Conversion',
    logo: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-5',
    name: 'PGS-India Organic (Full Certification)',
    type: 'NATIONAL',
    country: 'India',
    issuingAuthority: 'Ministry of Agriculture & Farmers Welfare, Govt of India',
    licenseNo: 'PGS-INDIA-ORG-2025-448',
    verifiedScore: 99,
    validUntil: '2028-06-30',
    badgeText: 'PGS-India Certified Organic',
    logo: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-6',
    name: 'INDOCERT Organic Certification',
    type: 'NATIONAL',
    country: 'India (Kerala & South Zone)',
    issuingAuthority: 'Indian Organic Certification Agency (INDOCERT)',
    licenseNo: 'INDOCERT-NPOP-0041',
    verifiedScore: 98,
    validUntil: '2027-12-31',
    badgeText: 'INDOCERT NPOP Verified',
    logo: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-7',
    name: 'Demeter Biodynamic Agriculture Seal',
    type: 'INTERNATIONAL',
    country: 'Global / Demeter India',
    issuingAuthority: 'Demeter International & Biodynamic Association of India',
    licenseNo: 'DEMETER-IND-99120',
    verifiedScore: 99.5,
    validUntil: '2028-10-31',
    badgeText: 'Demeter Biodynamic Certified',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-8',
    name: 'Sikkim 100% Organic State Standard (SSOCA)',
    type: 'LOCAL_GOV',
    country: 'India (Sikkim)',
    issuingAuthority: 'Sikkim State Organic Certification Agency',
    licenseNo: 'SSOCA-NPOP-0001',
    verifiedScore: 99.8,
    validUntil: '2029-01-31',
    badgeText: '100% Organic State Certified',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=100&auto=format&fit=crop&q=80',
  },
];

export const MOCK_FARMERS = [
  {
    id: 'usr_farmer_01',
    name: 'Ramesh Patel',
    phoneNumber: '+919876543210',
    email: 'ramesh.patel@ecoswadesh.com',
    location: 'Sehore, Madhya Pradesh, India',
    farmSizeAcres: 18.5,
    primaryCrops: ['Sharbati Wheat', 'Organic Soybean', 'Desi Chana'],
    certifications: ['NPOP/NAB/0014/2025', 'MP-AGRI-ORG-4402'],
    fpoName: 'Malwa Narmada Organic Farmers Producer Co. Ltd.',
    soilHealthCardId: 'SHC-MP-SEH-2025-08912',
    address: {
      village: 'Barkheda Hasan',
      gramPanchayat: 'Barkheda GP',
      tehsil: 'Sehore',
      district: 'Sehore',
      state: 'Madhya Pradesh',
      pinCode: '466001',
    },
  },
  {
    id: 'usr_farmer_02',
    name: 'Kongthong Synrem',
    phoneNumber: '+919833441122',
    email: 'kongthong.synrem@ecoswadesh.com',
    location: 'West Jaintia Hills, Meghalaya, India',
    farmSizeAcres: 6.2,
    primaryCrops: ['Lakadong High-Curcumin Turmeric', "Bird's Eye Chilli", 'Organic Ginger'],
    certifications: ['NPOP/NAB/0022/2025', 'MOVCDNER-MEGH-7781'],
    fpoName: 'Jaintia Organic Spices Farmer Producer Company',
    soilHealthCardId: 'SHC-MEG-JAI-2025-01442',
    address: {
      village: 'Lakadong',
      gramPanchayat: 'Shangpung GP',
      tehsil: 'Thadlaskein',
      district: 'West Jaintia Hills',
      state: 'Meghalaya',
      pinCode: '793150',
    },
  },
  {
    id: 'usr_farmer_03',
    name: 'Mahadev Tukaram Jadhav',
    phoneNumber: '+919822119933',
    email: 'mahadev.jadhav@ecoswadesh.com',
    location: 'Ratnagiri, Maharashtra, India',
    farmSizeAcres: 14.0,
    primaryCrops: ['GI Alphonso Mango (Hapus)', 'Organic Cashew', 'Kokum'],
    certifications: ['NPOP/NAB/0019/2025', 'MH-AGRI-ORG-5510'],
    fpoName: 'Konkan Krishi Ratna Organic FPO',
    soilHealthCardId: 'SHC-MH-RAT-2025-07731',
    address: {
      village: 'Pawani',
      gramPanchayat: 'Pawas Gram Panchayat',
      tehsil: 'Ratnagiri',
      district: 'Ratnagiri',
      state: 'Maharashtra',
      pinCode: '415616',
    },
  },
  {
    id: 'usr_farmer_04',
    name: 'Gurpreet Singh Dhillon',
    phoneNumber: '+919877223344',
    email: 'gurpreet.dhillon@ecoswadesh.com',
    location: 'Bathinda, Punjab, India',
    farmSizeAcres: 24.0,
    primaryCrops: ['Traditional Basmati 1121', 'Organic Mustard', 'Desi Moong'],
    certifications: ['NPOP/NAB/0009/2025', 'PB-AGRI-ORG-1029'],
    fpoName: 'Malwa Progressive Organic Growers Society',
    soilHealthCardId: 'SHC-PB-BAT-2025-03319',
    address: {
      village: 'Bhagwangarh',
      gramPanchayat: 'Talwandi Sabo GP',
      tehsil: 'Talwandi Sabo',
      district: 'Bathinda',
      state: 'Punjab',
      pinCode: '151302',
    },
  },
  {
    id: 'usr_farmer_16',
    name: 'Prataprao Chavan',
    phoneNumber: '+919823115544',
    email: 'prataprao.chavan@ecoswadesh.com',
    location: 'Sangli, Maharashtra, India',
    farmSizeAcres: 17.5,
    primaryCrops: ['Desi Khapli Wheat (Emmer)', 'Waigaon Turmeric', 'Organic Jaggery'],
    certifications: ['NPOP/NAB/0019/2025', 'MH-AGRI-ORG-3320'],
    fpoName: 'Krishna Valley Ancient Grains Producer Co.',
    soilHealthCardId: 'SHC-MH-SAN-2025-09141',
    address: {
      village: 'Walwa',
      gramPanchayat: 'Walwa Gram Panchayat',
      tehsil: 'Walwa',
      district: 'Sangli',
      state: 'Maharashtra',
      pinCode: '416313',
    },
  },
  {
    id: 'usr_farmer_17',
    name: 'C. K. Ramachandran',
    phoneNumber: '+919849227766',
    email: 'ck.ramachandran@ecoswadesh.com',
    location: 'Palakkad, Kerala, India',
    farmSizeAcres: 12.0,
    primaryCrops: ['GI Navara Medicinal Rice', 'GI Palakkadan Matta Rice', 'Organic Coconut'],
    certifications: ['INDOCERT-NPOP-0041', 'KL-AGRI-ORG-7782'],
    fpoName: 'Nila Ayurvedic Heritage Paddy Conservers FPC',
    soilHealthCardId: 'SHC-KL-PAL-2025-04419',
    address: {
      village: 'Chittur',
      gramPanchayat: 'Chittur-Thathamangalam GP',
      tehsil: 'Chittur',
      district: 'Palakkad',
      state: 'Kerala',
      pinCode: '678101',
    },
  },
  {
    id: 'usr_farmer_18',
    name: 'Bikram Senapati',
    phoneNumber: '+919835001199',
    email: 'bikram.senapati@ecoswadesh.com',
    location: 'Bastar, Chhattisgarh, India',
    farmSizeAcres: 8.0,
    primaryCrops: ['Organic Wild Forest Honey', 'Kodo-Kutki Millets', 'Mahuwa Flowers'],
    certifications: ['PGS-INDIA-ORG-CG-2025', 'NPOP/NAB/0031/2025'],
    fpoName: 'Dandakaranya Forest Bio-Treasures Cooperative',
    soilHealthCardId: 'SHC-CG-BAS-2025-01209',
    address: {
      village: 'Tokapal',
      gramPanchayat: 'Tokapal GP',
      tehsil: 'Tokapal',
      district: 'Bastar',
      state: 'Chhattisgarh',
      pinCode: '494001',
    },
  },
  {
    id: 'usr_farmer_19',
    name: 'Tashi Namgyal',
    phoneNumber: '+919832004488',
    email: 'tashi.namgyal@ecoswadesh.com',
    location: 'East Sikkim, Sikkim, India',
    farmSizeAcres: 5.5,
    primaryCrops: ['GI Sikkim Large Cardamom', 'Organic Ginger', 'Dalle Khursani Chilli'],
    certifications: ['SSOCA-NPOP-0001', 'SIKKIM-100-ORG-2025'],
    fpoName: 'Himalayan 100% Organic Spices Cultivators Union',
    soilHealthCardId: 'SHC-SK-EAS-2025-00812',
    address: {
      village: 'Rongli',
      gramPanchayat: 'Rongli Gram Panchayat',
      tehsil: 'Rongli',
      district: 'Pakyong (East Sikkim)',
      state: 'Sikkim',
      pinCode: '737131',
    },
  },
];

export const MOCK_PRODUCTS = [
  // Bulk Harvest
  {
    id: 'prod-1',
    name: 'Direct Farm Harvest: 100% Organic MP Sharbati Wheat',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_01',
    farmerName: 'Ramesh Patel',
    sellerName: 'Malwa Narmada Organic Farmers Producer Co. Ltd.',
    sellerType: 'Certified Organic Farmer Collective',
    origin: 'Sehore, Madhya Pradesh, India',
    rating: 4.95,
    reviewsCount: 148,
    certifiedType: 'NATIONAL',
    certName: 'Jaivik Bharat / NPOP Standard (APEDA)',
    certLicense: 'NPOP/NAB/0014/2025',
    labPurityRating: '100% Pesticide-Residue Free (0.00 ppm)',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80',
    retailPrice: 65,
    retailUnit: 'Kg',
    retailMinQty: 5,
    bulkAvailable: true,
    bulkPricePerTon: 42000,
    bulkMinTons: 5,
    bulkUnit: 'Ton',
    description: 'Golden, naturally sweet Sharbati wheat grown in the black soil plains of Sehore, MP. Cultivated using cow-dung Jeevamrutha and zero chemical synthetics.',
    inStock: true,
  },
  {
    id: 'prod-2',
    name: 'Aromatic Himalayan Traditional Basmati 1121 Paddy (Long Grain)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_04',
    farmerName: 'Gurpreet Singh Dhillon',
    sellerName: 'Malwa Progressive Organic Growers Society',
    sellerType: 'Certified Organic Farmer Collective',
    origin: 'Bathinda, Punjab, India',
    rating: 4.92,
    reviewsCount: 112,
    certifiedType: 'NATIONAL',
    certName: 'APEDA NPOP & Punjab Organic Board',
    certLicense: 'NPOP/NAB/0009/2025',
    labPurityRating: 'Aflatoxin & Heavy Metal Free (NABL Tested)',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    retailPrice: 95,
    retailUnit: 'Kg',
    retailMinQty: 5,
    bulkAvailable: true,
    bulkPricePerTon: 72000,
    bulkMinTons: 4,
    bulkUnit: 'Ton',
    description: 'Extra-long grain 8.4mm aged Basmati rice cultivated along canal waters with green manure and Trichoderma biological seed dressing.',
    inStock: true,
  },
  {
    id: 'prod-5',
    name: 'High-Curcumin Lakadong Turmeric Whole & Ground (Curcumin > 7.5%)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_02',
    farmerName: 'Kongthong Synrem',
    sellerName: 'Jaintia Organic Spices Farmer Producer Company',
    sellerType: 'Women Led Tribal FPO',
    origin: 'West Jaintia Hills, Meghalaya, India',
    rating: 4.99,
    reviewsCount: 220,
    certifiedType: 'NATIONAL',
    certName: 'NPOP TraceNet & Meghalaya Organic Mission',
    certLicense: 'NPOP/NAB/0022/2025',
    labPurityRating: 'HPLC Certified 7.82% Curcumin Content',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80',
    retailPrice: 380,
    retailUnit: 'Kg',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 280000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'World-renowned highest curcumin turmeric grown in pristine high-altitude organic hills of Jaintia. Zero lead chromate, 100% pure sun-dried rhizomes.',
    inStock: true,
  },
  {
    id: 'prod-9',
    name: 'Ancient Desi Khapli Wheat (Emmer / Low Glycemic Index & High Protein)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_16',
    farmerName: 'Prataprao Chavan',
    sellerName: 'Krishna Valley Ancient Grains Producer Co.',
    sellerType: 'Heirloom Grain Farmers Collective',
    origin: 'Sangli, Maharashtra, India',
    rating: 4.96,
    reviewsCount: 108,
    certifiedType: 'NATIONAL',
    certName: 'Jaivik Bharat / Maharashtra Organic Board',
    certLicense: 'MH-AGRI-ORG-3320',
    labPurityRating: '100% Unhybridized Heirloom Emmer Wheat',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80',
    retailPrice: 90,
    retailUnit: 'Kg',
    retailMinQty: 5,
    bulkAvailable: true,
    bulkPricePerTon: 68000,
    bulkMinTons: 3,
    bulkUnit: 'Ton',
    description: 'Traditional unhybridized Emmer wheat containing easily digestible gluten and high dietary fiber. Ideal for diabetic-friendly diets.',
    inStock: true,
  },
  {
    id: 'prod-10',
    name: 'GI Navara Medicinal Ayurvedic Heritage Rice (Red Husked)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_17',
    farmerName: 'C. K. Ramachandran',
    sellerName: 'Nila Ayurvedic Heritage Paddy Conservers FPC',
    sellerType: 'Medicinal Paddy Cultivators Union',
    origin: 'Palakkad, Kerala, India',
    rating: 4.99,
    reviewsCount: 145,
    certifiedType: 'NATIONAL',
    certName: 'INDOCERT NPOP & GI Tag No. 34',
    certLicense: 'INDOCERT-NPOP-0041',
    labPurityRating: 'Rich in Polyphenols, Zinc & Iron (100% Pure)',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    retailPrice: 220,
    retailUnit: 'Kg',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 165000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: '2000-year-old medicinal rice used in Ayurvedic Panchakarma treatments. Strengthens immune resistance and muscle tissue regeneration.',
    inStock: true,
  },
  {
    id: 'prod-11',
    name: 'Raw Unprocessed Bastar Wild Forest Honey (Multifloral Forest Flora)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_18',
    farmerName: 'Bikram Senapati',
    sellerName: 'Dandakaranya Forest Bio-Treasures Cooperative',
    sellerType: 'Tribal Honey Gatherers Union',
    origin: 'Bastar, Chhattisgarh, India',
    rating: 4.98,
    reviewsCount: 180,
    certifiedType: 'NATIONAL',
    certName: 'TRIFED Organic & PGS-India Certified',
    certLicense: 'PGS-INDIA-ORG-CG-2025',
    labPurityRating: 'Zero Sugar Adulteration / C4 Sugar Negative (NABL NMR Tested)',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80',
    retailPrice: 550,
    retailUnit: 'Kg (Glass Jar)',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 390000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Raw, unpasteurized forest honey gathered from wild Apis dorsata bee colonies in the deep forests of Bastar. Packed with live enzymes and natural pollen.',
    inStock: true,
  },

  // Fertilizers
  {
    id: 'prod-13',
    name: 'Bio-Active NPK Liquid Organic Fertilizer',
    category: 'fertilizers',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Gujarat, India',
    rating: 4.9,
    reviewsCount: 142,
    certifiedType: 'NATIONAL',
    certName: 'Jaivik Bharat & USDA Organic',
    certLicense: 'NPOP/NAB/0014/2025',
    labPurityRating: '99.4% Chemical-Free / Bacterial Count 1x10^9 CFU/ml',
    image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?w=600&auto=format&fit=crop&q=80',
    retailPrice: 450,
    retailUnit: 'Liter',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 85000,
    bulkMinTons: 2,
    bulkUnit: 'Ton',
    description: 'High-potency microbial nitrogen, phosphorus, and potassium liquid fertilizer. Enhances root mass by 40% and boosts soil organic carbon naturally.',
    npkRatio: 'N: 6% | P: 4% | K: 8%',
    usageDose: '5 ml per liter of irrigation water or 200 Liters per acre via drip.',
    inStock: true,
  },
  {
    id: 'prod-14',
    name: 'Premium Vermicompost Soil Conditioner (Enriched with Humic Acid)',
    category: 'fertilizers',
    farmerId: 'usr_farmer_01',
    farmerName: 'Ramesh Patel',
    sellerName: 'EarthWorm Gold Farmers Union',
    sellerType: 'Local Farmer Cooperative',
    origin: 'Madhya Pradesh, India',
    rating: 4.85,
    reviewsCount: 210,
    certifiedType: 'LOCAL_GOV',
    certName: 'MP State Organic Agriculture Council',
    certLicense: 'MP-AGRI-ORG-4402',
    labPurityRating: '100% Pure Worm Castings, C:N Ratio 14:1',
    image: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?w=600&auto=format&fit=crop&q=80',
    retailPrice: 25,
    retailUnit: 'Kg Bag',
    retailMinQty: 5,
    bulkAvailable: true,
    bulkPricePerTon: 12500,
    bulkMinTons: 3,
    bulkUnit: 'Ton',
    description: 'Rich dark humus created by Eisenia Fetida earthworms fed on cow dung and neem leaves. Loaded with beneficial mycorrhizae and humic substances.',
    inStock: true,
  },
  {
    id: 'prod-16',
    name: 'Pure Seaweed Extract Bio-Stimulant & Plant Growth Booster',
    category: 'fertilizers',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Tamil Nadu, India',
    rating: 4.93,
    reviewsCount: 115,
    certifiedType: 'NATIONAL',
    certName: 'ICAR-CMFRI Certified Organic Bio-Input',
    certLicense: 'NPOP/NAB/0014/2025',
    labPurityRating: 'Alginic Acid 18%, Mannitol 5%, Cytokinins Active',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    retailPrice: 680,
    retailUnit: 'Liter Bottle',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 195000,
    bulkMinTons: 1,
    bulkUnit: 'Ton (Barrels)',
    description: 'Concentrated marine kelp extract loaded with natural auxins, betaines, and 60+ trace minerals to trigger flower retention and fruit sizing.',
    inStock: true,
  },
  {
    id: 'prod-18',
    name: 'VAM Endomycorrhiza Bio-Fertilizer (Root Extension Granules)',
    category: 'fertilizers',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Karnataka, India',
    rating: 4.95,
    reviewsCount: 89,
    certifiedType: 'NATIONAL',
    certName: 'Jaivik Bharat & NCOF Registered',
    certLicense: 'NCOF-BIO-VAM-2025',
    labPurityRating: 'Infectivity 100 IP/g (Glomus intraradices)',
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23998?w=600&auto=format&fit=crop&q=80',
    retailPrice: 180,
    retailUnit: 'Kg Pack',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 115000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Symbiotic root-colonizing mycorrhizal fungus that expands the effective root surface area by 100x, boosting water and zinc/phosphate absorption.',
    inStock: true,
  },

  // Bio-Pesticides
  {
    id: 'prod-19',
    name: 'Neem-Shield Bio-Pesticide & Cold-Pressed Neem Oil (10,000 PPM)',
    category: 'bioPesticides',
    sellerName: 'NeemTech Organics Ltd.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Rajasthan, India',
    rating: 4.9,
    reviewsCount: 96,
    certifiedType: 'NATIONAL',
    certName: 'USDA NOP & EU Bio Standards',
    certLicense: 'USDA-NOP-884920-US',
    labPurityRating: '10,000 PPM Azadirachtin',
    image: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=600&auto=format&fit=crop&q=80',
    retailPrice: 380,
    retailUnit: '500ml Bottle',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 110000,
    bulkMinTons: 1,
    bulkUnit: 'Ton (Barrel Pack)',
    description: 'Broad-spectrum botanical pesticide effective against caterpillars, aphids, thrips, and whiteflies. Safe for beneficial pollinators like bees.',
    inStock: true,
  },
  {
    id: 'prod-20',
    name: 'Trichoderma Viride 1.5% WP (Bio-Fungicide for Root Rot & Wilt)',
    category: 'bioPesticides',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Control Lab',
    origin: 'Maharashtra, India',
    rating: 4.92,
    reviewsCount: 104,
    certifiedType: 'NATIONAL',
    certName: 'CIB&RC Registered & Jaivik Bharat',
    certLicense: 'CIBRC-BIO-2025-881',
    labPurityRating: 'Spore Count 2x10^6 CFU/g Min',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    retailPrice: 220,
    retailUnit: 'Kg Pack',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 140000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Antagonistic bio-control fungus that prevents Fusarium wilt, Rhizoctonia root rot, and damping-off across pulses, cotton, and vegetables.',
    inStock: true,
  },
  {
    id: 'prod-22',
    name: 'Beauveria Bassiana 1.15% WP (Entomopathogenic Bio-Insecticide)',
    category: 'bioPesticides',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Control Lab',
    origin: 'Karnataka, India',
    rating: 4.94,
    reviewsCount: 73,
    certifiedType: 'NATIONAL',
    certName: 'CIB&RC Registered & NPOP Approved',
    certLicense: 'CIBRC-BIO-2025-912',
    labPurityRating: 'Spore Viability 1x10^8 CFU/g',
    image: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=600&auto=format&fit=crop&q=80',
    retailPrice: 290,
    retailUnit: 'Kg Pack',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 175000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'White muscardine entomopathogenic fungus that parasitizes bollworms, thrips, whiteflies, and diamondback moths through cuticle penetration.',
    inStock: true,
  },
  {
    id: 'prod-23',
    name: 'Dashaparni Organic Botanical Herbal Extract (10-Leaf Kashayam)',
    category: 'bioPesticides',
    farmerId: 'usr_farmer_01',
    farmerName: 'Ramesh Patel',
    sellerName: 'Malwa Narmada Organic Farmers Producer Co. Ltd.',
    sellerType: 'Farmer Producer Collective',
    origin: 'Madhya Pradesh, India',
    rating: 4.96,
    reviewsCount: 110,
    certifiedType: 'NATIONAL',
    certName: 'PGS-India Verified Herbal Formulation',
    certLicense: 'PGS-INDIA-ORG-2025-448',
    labPurityRating: '100% Botanical Ferment (Neem, Karanj, Calotropis, Castor)',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    retailPrice: 320,
    retailUnit: '1 Liter Bottle',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 95000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Vedic 10-leaf fermented bio-pesticide concoction that acts as a natural antifeedant, oviposition deterrent, and insect repellent.',
    inStock: true,
  },

  // Seeds
  {
    id: 'prod-24',
    name: 'High-Yield Hybrid Organic Tomato Seeds (F1 Wilt Resistant)',
    category: 'seeds',
    sellerName: 'Vedic Seed Innovations',
    sellerType: 'Seed Nursery & Breeder',
    origin: 'Karnataka, India',
    rating: 4.9,
    reviewsCount: 175,
    certifiedType: 'NATIONAL',
    certName: 'National Seed Certification Board',
    certLicense: 'NSCB-IND-99120',
    labPurityRating: '98% Germination Guaranteed',
    image: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&auto=format&fit=crop&q=80',
    retailPrice: 220,
    retailUnit: '10g Packet',
    retailMinQty: 1,
    bulkAvailable: false,
    description: 'High-yielding semi-determinate tomato seeds bred for wilt resistance and intense flavor. Suitable for open field and greenhouse cultivation.',
    inStock: true,
  },
  {
    id: 'prod-25',
    name: 'Indigenous Desi Cotton Seeds (Suvin & Karunganni Varieties)',
    category: 'seeds',
    farmerId: 'usr_farmer_14',
    farmerName: 'Devendra Bhaskarrao Patil',
    sellerName: 'Vidarbha Organic Cotton Growers Mahasangh',
    sellerType: 'Indigenous Seed Conservers Collective',
    origin: 'Maharashtra, India',
    rating: 4.94,
    reviewsCount: 65,
    certifiedType: 'NATIONAL',
    certName: 'National Bureau of Plant Genetic Resources (NBPGR)',
    certLicense: 'NBPGR-IND-DESI-2025',
    labPurityRating: '100% Non-GMO Heritage Variety Germination 92%',
    image: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=600&auto=format&fit=crop&q=80',
    retailPrice: 450,
    retailUnit: '500g Packet',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 350000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Drought-tolerant heirloom Indian desi cotton seeds. Naturally resistant to bollworm without chemical sprays.',
    inStock: true,
  },
  {
    id: 'prod-26',
    name: 'Organic Finger Millet (Ragi GPU-28 Certified Drought-Hardy Seeds)',
    category: 'seeds',
    farmerId: 'usr_farmer_07',
    farmerName: 'Subhashree Mohapatra',
    sellerName: 'Sabari Tribal Organic Farmers Producer Collective',
    sellerType: 'Indigenous Seed Bank Cooperative',
    origin: 'Odisha, India',
    rating: 4.92,
    reviewsCount: 88,
    certifiedType: 'NATIONAL',
    certName: 'ICAR-IIMR Millet Certified Variety',
    certLicense: 'ICAR-IIMR-RAGI-2025',
    labPurityRating: 'Germination Rate 96%, Moisture 10%',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    retailPrice: 160,
    retailUnit: '1 Kg Packet',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 85000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Short-duration, blast-tolerant traditional finger millet seeds with exceptional calcium and dietary fiber yielding capacity.',
    inStock: true,
  },
  {
    id: 'prod-27',
    name: 'Heirloom Mattu Gulla GI Brinjal Seeds (Green Striped Variety)',
    category: 'seeds',
    farmerId: 'usr_farmer_09',
    farmerName: 'Manjunath Hegde',
    sellerName: 'Sahyadri Organic Spices & Plantation FPC',
    sellerType: 'Heirloom Seed Conservers',
    origin: 'Karnataka, India',
    rating: 4.97,
    reviewsCount: 54,
    certifiedType: 'NATIONAL',
    certName: 'GI Tag Heritage Seed Registry',
    certLicense: 'GI-SEED-MATTU-2025',
    labPurityRating: '100% Pure Mattu Gulla Heirloom Strain',
    image: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&auto=format&fit=crop&q=80',
    retailPrice: 180,
    retailUnit: '25g Packet',
    retailMinQty: 1,
    bulkAvailable: false,
    description: 'Famed 400-year-old GI-tagged light green striped spherical brinjal seeds known for tender texture and delicate sweet flavor.',
    inStock: true,
  },

  // Equipment
  {
    id: 'prod-28',
    name: 'Solar-Powered Automated Drip Irrigation Kit (1 Acre)',
    category: 'equipment',
    sellerName: 'SunAgro Tech Systems',
    sellerType: 'Equipment Supplier',
    origin: 'Maharashtra, India',
    rating: 4.85,
    reviewsCount: 54,
    certifiedType: 'NATIONAL',
    certName: 'Bureau of Indian Standards (BIS Certified)',
    certLicense: 'BIS-AGRI-44120',
    labPurityRating: 'ISO 9001:2025 Quality Passed',
    image: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=600&auto=format&fit=crop&q=80',
    retailPrice: 24500,
    retailUnit: 'Full Kit (1 Acre)',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 215000,
    bulkMinTons: 1,
    bulkUnit: 'Set of 10 Acres',
    description: 'Complete water-saving precision drip irrigation system with automatic solar timer pump. Reduces water usage by up to 60%.',
    inStock: true,
  },
  {
    id: 'prod-29',
    name: 'Handheld Mobile Digital Soil NPK & pH Spectrometer',
    category: 'equipment',
    sellerName: 'AgroSensor Photonics Labs',
    sellerType: 'Precision Agri-Tech Manufacturer',
    origin: 'Karnataka, India',
    rating: 4.96,
    reviewsCount: 39,
    certifiedType: 'NATIONAL',
    certName: 'ICAR-IARI Calibrated & CE Certified',
    certLicense: 'ICAR-AGRI-TECH-2025-081',
    labPurityRating: '98.5% Correlation with NABL Wet Lab Tests',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    retailPrice: 18500,
    retailUnit: '1 Device Kit',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 160000,
    bulkMinTons: 1,
    bulkUnit: 'Box of 10 Units',
    description: 'Instant 45-second optical soil health testing scanner. Syncs via Bluetooth to the Eco Swadesh app for automated dosage generation.',
    inStock: true,
  },
  {
    id: 'prod-30',
    name: 'Electric Bio-Waste Shredder & Compost Chaff Cutter (3 HP)',
    category: 'equipment',
    sellerName: 'SunAgro Tech Systems',
    sellerType: 'Agri-Machinery Manufacturer',
    origin: 'Punjab, India',
    rating: 4.91,
    reviewsCount: 42,
    certifiedType: 'NATIONAL',
    certName: 'Govt FMTTI Certified Agri Machinery',
    certLicense: 'FMTTI-SHREDDER-2025-44',
    labPurityRating: 'Heavy-Duty Carbon Steel Blades (Shred Rate 500 Kg/Hr)',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    retailPrice: 32000,
    retailUnit: '1 Unit Machine',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 280000,
    bulkMinTons: 1,
    bulkUnit: 'Set of 10 Units',
    description: 'High-speed organic residue and crop-straw shredder for preparing fast vermicompost feeding beds and biochar raw material.',
    inStock: true,
  },
  {
    id: 'prod-31',
    name: 'Solar-Powered Automatic LED Insect Light Trap (1 Acre Protection)',
    category: 'equipment',
    sellerName: 'AgroSensor Photonics Labs',
    sellerType: 'Solar Pest Solutions',
    origin: 'Gujarat, India',
    rating: 4.88,
    reviewsCount: 61,
    certifiedType: 'NATIONAL',
    certName: 'National Organic Input Verification Board',
    certLicense: 'NOIVB-SOLAR-2025',
    labPurityRating: 'Auto Dusk-to-Dawn Optical Sensor (Pest Catch Range 1 Acre)',
    image: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=600&auto=format&fit=crop&q=80',
    retailPrice: 4200,
    retailUnit: '1 Unit Trap Kit',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 360000,
    bulkMinTons: 1,
    bulkUnit: 'Lot of 100 Traps',
    description: 'Chemical-free biological pest management light trap with automated solar panel and high-voltage grid funnel. Attracts and eliminates nocturnal moths.',
    inStock: true,
  },
  {
    id: 'prod-32',
    name: 'Autonomous Agricultural Drone Bio-Sprayer (16L Tank)',
    category: 'equipment',
    sellerName: 'SunAgro Tech Systems',
    sellerType: 'Precision Aero-Tech Systems',
    origin: 'Telangana, India',
    rating: 4.98,
    reviewsCount: 28,
    certifiedType: 'NATIONAL',
    certName: 'DGCA Type Certified Agriculture Drone',
    certLicense: 'DGCA-AGRI-DRONE-2025-019',
    labPurityRating: 'Precision Spray Droplet Size 100-250 Microns',
    image: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=600&auto=format&fit=crop&q=80',
    retailPrice: 480000,
    retailUnit: 'Complete Drone & 3 Battery Pack',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 4400000,
    bulkMinTons: 1,
    bulkUnit: 'Fleet of 10 Drones',
    description: 'DGCA-certified drone engineered specifically for spraying microbial bio-fertilizers, neem extracts, and Trichoderma solutions over 25 acres per day.',
    inStock: true,
  },
];

export const MOCK_COMMODITY_PRICES = [
  { crop: 'Organic Wheat (MP Sharbati - Sehore)', priceRetail: '₹65 / Kg', priceBulk: '₹42,000 / Ton', change: '+2.4%', trend: 'up', mandiBenchmark: '₹41,200 / Ton' },
  { crop: 'Organic Basmati Paddy Rice (1121)', priceRetail: '₹95 / Kg', priceBulk: '₹72,000 / Ton', change: '+3.1%', trend: 'up', mandiBenchmark: '₹69,500 / Ton' },
  { crop: 'Ancient Desi Khapli Wheat (Emmer)', priceRetail: '₹90 / Kg', priceBulk: '₹68,000 / Ton', change: '+1.9%', trend: 'up', mandiBenchmark: '₹66,000 / Ton' },
  { crop: 'Lakadong Turmeric (Jaintia Hills)', priceRetail: '₹380 / Kg', priceBulk: '₹280,000 / Ton', change: '+4.5%', trend: 'up', mandiBenchmark: '₹270,000 / Ton' },
  { crop: 'Malabar Black Pepper (Wayanad)', priceRetail: '₹620 / Kg', priceBulk: '₹490,000 / Ton', change: '+1.8%', trend: 'up', mandiBenchmark: '₹480,000 / Ton' },
  { crop: 'Alphonso Mango (Ratnagiri Hapus)', priceRetail: '₹1,200 / Doz', priceBulk: '₹180,000 / Ton', change: '+5.2%', trend: 'up', mandiBenchmark: '₹172,000 / Ton' },
  { crop: 'Koraput Kalajeera Heritage Rice', priceRetail: '₹140 / Kg', priceBulk: '₹98,000 / Ton', change: '+0.5%', trend: 'stable', mandiBenchmark: '₹96,000 / Ton' },
  { crop: 'Kashmiri Mongra Saffron (Pampore)', priceRetail: '₹350 / Gram', priceBulk: '₹240,000 / Kg', change: '+1.2%', trend: 'up', mandiBenchmark: '₹235,000 / Kg' },
  { crop: 'GI Navara Medicinal Rice (Kerala)', priceRetail: '₹220 / Kg', priceBulk: '₹165,000 / Ton', change: '+2.0%', trend: 'up', mandiBenchmark: '₹160,000 / Ton' },
  { crop: 'Bastar Wild Forest Honey', priceRetail: '₹550 / Kg', priceBulk: '₹390,000 / Ton', change: '+0.8%', trend: 'up', mandiBenchmark: '₹385,000 / Ton' },
  { crop: 'Sikkim Large Cardamom (Bara Elaichi)', priceRetail: '₹1,450 / Kg', priceBulk: '₹1,150,000 / Ton', change: '+3.4%', trend: 'up', mandiBenchmark: '₹1,120,000 / Ton' },
  { crop: 'Organic Desi Raw Cotton (Vidarbha)', priceRetail: '₹120 / Kg', priceBulk: '₹88,000 / Ton', change: '-1.1%', trend: 'down', mandiBenchmark: '₹86,500 / Ton' },
  { crop: 'Bio-NPK Liquid Fertilizer Consortium', priceRetail: '₹450 / Liter', priceBulk: '₹85,000 / Ton', change: '-0.8%', trend: 'down', mandiBenchmark: '₹88,000 / Ton' },
  { crop: 'Organic Vermicompost Humic Plus', priceRetail: '₹25 / Kg', priceBulk: '₹12,500 / Ton', change: '+1.5%', trend: 'up', mandiBenchmark: '₹12,000 / Ton' },
  { crop: 'Cold-Pressed Neem Oil (10,000 PPM)', priceRetail: '₹380 / 500ml', priceBulk: '₹110,000 / Ton', change: '0.0%', trend: 'stable', mandiBenchmark: '₹112,000 / Ton' },
];

export const MOCK_SHIPMENTS = [
  {
    id: 'SHIP-8921',
    type: 'BULK_FREIGHT',
    title: '15 Tons Organic Sharbati Wheat Truckload',
    origin: 'Farm #4, Barkheda Hasan, Sehore, MP',
    destination: 'AgroProcessor Flour Mill Warehouse, Pune, MH',
    weight: '15.0 Tons',
    carrier: 'EcoFreight Heavy Trucking Direct',
    status: 'IN_TRANSIT',
    driverName: 'Ramesh Singh',
    driverPhone: '+91 98230 11200',
    vehicleNo: 'MH-12-VT-9921',
    estDelivery: 'Tomorrow, 04:30 PM',
    escrowStatus: '₹6,30,000 Held in Escrow (Release after destination lab check)',
    milestones: [
      { label: 'Harvest Loaded at Farm (Sehore)', date: '24 Jul, 08:00 AM', completed: true },
      { label: 'Weighbridge & Initial APEDA Seal Check', date: '24 Jul, 11:30 AM', completed: true },
      { label: 'En-Route on Highway NH-52', date: '24 Jul, 04:00 PM', completed: true },
      { label: 'Destination Lab Check at Warehouse', date: '25 Jul, 02:00 PM', completed: false },
      { label: 'Final Escrow Release to Farmer', date: '25 Jul, 05:00 PM', completed: false },
    ],
  },
  {
    id: 'SHIP-4402',
    type: 'RETAIL_PARCEL',
    title: '5 Liters Bio-NPK Liquid & 2 Kg Vermicompost',
    origin: 'GreenBio Earth Depot, Ahmedabad, GJ',
    destination: 'Sunshine Heights, Bandra West, Mumbai, MH',
    weight: '7.2 Kg',
    carrier: 'GreenParcel Carbon-Neutral Courier',
    status: 'DISPATCHED',
    trackingNo: 'GP-992018442-IN',
    estDelivery: '26 Jul, 02:00 PM',
    escrowStatus: 'Payment Completed via UPI',
    milestones: [
      { label: 'Order Confirmed', date: '23 Jul, 02:15 PM', completed: true },
      { label: 'Lab Sealed & Packaged with Anti-Counterfeit QR', date: '24 Jul, 09:00 AM', completed: true },
      { label: 'Dispatched via GreenParcel Express', date: '24 Jul, 01:00 PM', completed: true },
      { label: 'Out for Last-Mile Delivery', date: '26 Jul, 09:00 AM', completed: false },
    ],
  },
];

export const MOCK_COMMUNITY_POSTS = [
  {
    id: 'post-1',
    author: 'Dr. Anita Deshmukh',
    role: 'Agri-Expert & Soil Microbiologist',
    verifiedExpert: true,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    title: 'How to transition 5 acres from chemical farming to 100% Certified Organic without yield drop',
    content: 'Transitioning requires a 3-phase soil rejuvenation strategy. Start with bio-char and vermicompost to reseed beneficial mycorrhizae bacteria before cutting synthetic nitrogen. Within 120 days, soil organic carbon rises by 0.4% which stabilizes yields.',
    tags: ['Soil Health', 'Organic Transition', 'Bio-Fertilizers'],
    upvotes: 246,
    repliesCount: 38,
    date: '2 hours ago',
  },
  {
    id: 'post-2',
    author: 'Gurpreet Singh Dhillon',
    role: 'Organic Basmati Paddy Farmer',
    verifiedExpert: false,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    title: 'Direct Bulk Sales Experience: Bypassing Mandi Middlemen for 18 Tons of Basmati Paddy',
    content: 'Used Eco Swadesh Direct Freight last week to supply 18 Tons of organic basmati directly to a Pune flour mill. Escrow payment was released within 2 hours of lab test at warehouse! Received ₹72,000/Ton instead of ₹52,000 at local mandi.',
    tags: ['Direct Bulk Trade', 'Zero Middlemen', 'Escrow Payment', 'Basmati Rice'],
    upvotes: 189,
    repliesCount: 24,
    date: '5 hours ago',
  },
  {
    id: 'post-3',
    author: 'Kongthong Synrem',
    role: 'Lakadong Turmeric FPO Lead',
    verifiedExpert: false,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    title: 'Lakadong Turmeric Cooperative Export Story: From Jaintia Hills to Global B2B Buyers',
    content: 'Through our FPO and Eco Swadesh APEDA digital verification, 120 tribal women farmers successfully dispatched 8 Tons of 7.8% curcumin turmeric rhizomes at guaranteed premium pricing under smart escrow contract.',
    tags: ['Lakadong Turmeric', 'Tribal Women FPO', 'APEDA NPOP Export', 'Fair Trade'],
    upvotes: 312,
    repliesCount: 45,
    date: '1 day ago',
  },
  {
    id: 'post-4',
    author: 'Prataprao Chavan',
    role: 'Ancient Grains Farmer Lead',
    verifiedExpert: false,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    title: 'Reviving Ancient Khapli Wheat: High Market Demand & Zero Chemical Input Experience',
    content: 'Our Sangli collective transitioned 45 acres to indigenous Khapli (Emmer) wheat. Because Khapli has natural resistance to rust and pests, input costs dropped by 70%, while bulk buyers offered ₹68,000/Ton compared to ₹26,000 for hybrid wheat.',
    tags: ['Ancient Grains', 'Khapli Wheat', 'Low Glycemic', 'Farmer Profits'],
    upvotes: 278,
    repliesCount: 31,
    date: '2 days ago',
  },
];

export const MOCK_AI_DIAGNOSES = [
  {
    id: 'diag-1',
    cropName: 'Tomato Plant (Solanum lycopersicum)',
    detectedDisease: 'Early Blight (Alternaria solani)',
    confidence: '96.8% Accuracy',
    severity: 'Moderate Infection',
    organicCure: [
      'Spray 5ml/L Cold-Pressed Neem Oil (10,000 PPM) every 5 days.',
      'Apply Trichoderma viride bio-fungicide to soil near root zone.',
      'Remove lower infected yellow leaves and maintain proper spacing for airflow.',
    ],
    recommendedFertilizer: 'Bio-Active Potassium & Seaweed Extract for immunity boost.',
  },
  {
    id: 'diag-2',
    cropName: 'Cotton Plant (Gossypium hirsutum)',
    detectedDisease: 'Bacterial Blight & Whitefly Nymphs',
    confidence: '94.2% Accuracy',
    severity: 'Early Warning',
    organicCure: [
      'Apply 5% Neem Seed Kernel Extract (NSKE) spray at sunset.',
      'Install 15 yellow sticky traps per acre at canopy height.',
      'Release green lacewing predatory larvae for biological control.',
    ],
    recommendedFertilizer: 'Bio-NPK Liquid foliar spray at 4ml/Liter water.',
  },
  {
    id: 'diag-3',
    cropName: 'Turmeric Plant (Curcuma longa)',
    detectedDisease: 'Rhizome Rot (Pythium aphanidermatum)',
    confidence: '95.4% Accuracy',
    severity: 'Moderate Hazard',
    organicCure: [
      'Drench root rhizosphere with Trichoderma viride & Pseudomonas fluorescens @ 10g/Litre water.',
      'Improve soil drainage to prevent waterlogging.',
      'Dust bed with organic Neem Seed Cake powder @ 200 Kg/acre.',
    ],
    recommendedFertilizer: 'Humic-Enriched Vermicompost with bio-potash.',
  },
];
