/**
 * Eco Swadesh - Comprehensive Seed Dataset (Multi-Category Expanded Edition)
 * Contains 20+ verified organic farmers/FPOs across 18 Indian States/UTs,
 * 40+ certified organic products across 5 core categories (bulkHarvest, fertilizers,
 * bioPesticides, seeds, equipment), 12 national/international certifications,
 * real-time Mandi commodity price indices, shipments, AI diagnoses, and audit logs.
 */

const SEED_USERS = [
  {
    id: 'usr_farmer_01',
    phoneNumber: '+919876543210',
    countryCode: 'IN',
    name: 'Ramesh Patel',
    email: 'ramesh.patel@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Sehore, Madhya Pradesh, India',
    farmSizeAcres: 18.5,
    primaryCrops: ['Sharbati Wheat', 'Organic Soybean', 'Desi Chana'],
    certifications: ['NPOP/NAB/0014/2025', 'MP-AGRI-ORG-4402'],
    fpoName: 'Malwa Narmada Organic Farmers Producer Co. Ltd.',
    soilHealthCardId: 'SHC-MP-SEH-2025-08912',
    address: {
      village: 'Barkheda Hasan',
      gramPanchayat: 'Barkheda GP',
      tehsil: 'Sehore',
      district: 'Sehore',
      state: 'Madhya Pradesh',
      pinCode: '466001',
      coordinates: { latitude: 23.2032, longitude: 77.0844 },
    },
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'usr_farmer_02',
    phoneNumber: '+919833441122',
    countryCode: 'IN',
    name: 'Kongthong Synrem',
    email: 'kongthong.synrem@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'West Jaintia Hills, Meghalaya, India',
    farmSizeAcres: 6.2,
    primaryCrops: ['Lakadong High-Curcumin Turmeric', "Bird's Eye Chilli", 'Organic Ginger'],
    certifications: ['NPOP/NAB/0022/2025', 'MOVCDNER-MEGH-7781'],
    fpoName: 'Jaintia Organic Spices Farmer Producer Company',
    soilHealthCardId: 'SHC-MEG-JAI-2025-01442',
    address: {
      village: 'Lakadong',
      gramPanchayat: 'Shangpung GP',
      tehsil: 'Thadlaskein',
      district: 'West Jaintia Hills',
      state: 'Meghalaya',
      pinCode: '793150',
      coordinates: { latitude: 25.4670, longitude: 92.2045 },
    },
    createdAt: '2026-01-18T09:30:00Z',
  },
  {
    id: 'usr_farmer_03',
    phoneNumber: '+919822119933',
    countryCode: 'IN',
    name: 'Mahadev Tukaram Jadhav',
    email: 'mahadev.jadhav@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Ratnagiri, Maharashtra, India',
    farmSizeAcres: 14.0,
    primaryCrops: ['GI Alphonso Mango (Hapus)', 'Organic Cashew', 'Kokum'],
    certifications: ['NPOP/NAB/0019/2025', 'MH-AGRI-ORG-5510'],
    fpoName: 'Konkan Krishi Ratna Organic FPO',
    soilHealthCardId: 'SHC-MH-RAT-2025-07731',
    address: {
      village: 'Pawani',
      gramPanchayat: 'Pawas Gram Panchayat',
      tehsil: 'Ratnagiri',
      district: 'Ratnagiri',
      state: 'Maharashtra',
      pinCode: '415616',
      coordinates: { latitude: 16.9902, longitude: 73.3120 },
    },
    createdAt: '2026-01-20T10:15:00Z',
  },
  {
    id: 'usr_farmer_04',
    phoneNumber: '+919877223344',
    countryCode: 'IN',
    name: 'Gurpreet Singh Dhillon',
    email: 'gurpreet.dhillon@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Bathinda, Punjab, India',
    farmSizeAcres: 24.0,
    primaryCrops: ['Traditional Basmati 1121', 'Organic Mustard', 'Desi Moong'],
    certifications: ['NPOP/NAB/0009/2025', 'PB-AGRI-ORG-1029'],
    fpoName: 'Malwa Progressive Organic Growers Society',
    soilHealthCardId: 'SHC-PB-BAT-2025-03319',
    address: {
      village: 'Bhagwangarh',
      gramPanchayat: 'Talwandi Sabo GP',
      tehsil: 'Talwandi Sabo',
      district: 'Bathinda',
      state: 'Punjab',
      pinCode: '151302',
      coordinates: { latitude: 29.9833, longitude: 75.0833 },
    },
    createdAt: '2026-01-25T11:00:00Z',
  },
  {
    id: 'usr_farmer_05',
    phoneNumber: '+919829001122',
    countryCode: 'IN',
    name: 'Kailash Ram Bishnoi',
    email: 'kailash.bishnoi@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Nagaur, Rajasthan, India',
    farmSizeAcres: 32.0,
    primaryCrops: ['Organic Cumin (Jeera)', 'Desi Bajra', 'Isabgol (Psyllium)'],
    certifications: ['PGS-INDIA-ORG-RJ-8812', 'NPOP/NAB/0016/2025'],
    fpoName: 'Marwar Organic Seed Producers Co-Op',
    soilHealthCardId: 'SHC-RJ-NAG-2025-05512',
    address: {
      village: 'Merta Road',
      gramPanchayat: 'Merta Gram Panchayat',
      tehsil: 'Merta',
      district: 'Nagaur',
      state: 'Rajasthan',
      pinCode: '341510',
      coordinates: { latitude: 26.6500, longitude: 74.0333 },
    },
    createdAt: '2026-02-01T08:45:00Z',
  },
  {
    id: 'usr_farmer_06',
    phoneNumber: '+919847112233',
    countryCode: 'IN',
    name: 'Thresiamma Mathew',
    email: 'thresiamma.mathew@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Wayanad, Kerala, India',
    farmSizeAcres: 8.5,
    primaryCrops: ['GI Malabar Black Pepper', 'Tellicherry Extra Bold Cardamom', 'Organic Robusta Coffee'],
    certifications: ['INDOCERT-NPOP-0041', 'KL-AGRI-ORG-3312'],
    fpoName: 'Wayanad Bio-Spices & Coffee Producers Union',
    soilHealthCardId: 'SHC-KL-WAY-2025-09921',
    address: {
      village: 'Meppadi',
      gramPanchayat: 'Meppadi GP',
      tehsil: 'Vythiri',
      district: 'Wayanad',
      state: 'Kerala',
      pinCode: '673577',
      coordinates: { latitude: 11.5510, longitude: 76.1264 },
    },
    createdAt: '2026-02-03T14:20:00Z',
  },
  {
    id: 'usr_farmer_07',
    phoneNumber: '+919861334455',
    countryCode: 'IN',
    name: 'Subhashree Mohapatra',
    email: 'subhashree.mohapatra@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Koraput, Odisha, India',
    farmSizeAcres: 11.0,
    primaryCrops: ['GI Koraput Kalajeera Rice (Prince of Rice)', 'Kandhamal Haldi', 'Finger Millet (Ragi)'],
    certifications: ['PGS-INDIA-ORG-OD-4409', 'NPOP/NAB/0031/2025'],
    fpoName: 'Sabari Tribal Organic Farmers Producer Collective',
    soilHealthCardId: 'SHC-OD-KOR-2025-02194',
    address: {
      village: 'Kundura',
      gramPanchayat: 'Kundura GP',
      tehsil: 'Jeypore',
      district: 'Koraput',
      state: 'Odisha',
      pinCode: '764002',
      coordinates: { latitude: 18.8573, longitude: 82.5684 },
    },
    createdAt: '2026-02-05T09:10:00Z',
  },
  {
    id: 'usr_farmer_08',
    phoneNumber: '+919825114477',
    countryCode: 'IN',
    name: 'Gopalbhai Vaghani',
    email: 'gopalbhai.vaghani@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Talala Gir, Gir Somnath, Gujarat, India',
    farmSizeAcres: 22.0,
    primaryCrops: ['GI Gir Kesar Mango', 'Organic Groundnut (Saurashtra Bold)', 'Desi Sesame'],
    certifications: ['NPOP/NAB/0014/2025', 'GJ-AGRI-ORG-9901'],
    fpoName: 'Gir Somnath Jaivik Bagayatdar Sahakari Mandali',
    soilHealthCardId: 'SHC-GJ-GIR-2025-06631',
    address: {
      village: 'Bhalchhel',
      gramPanchayat: 'Talala GP',
      tehsil: 'Talala',
      district: 'Gir Somnath',
      state: 'Gujarat',
      pinCode: '362150',
      coordinates: { latitude: 21.0528, longitude: 70.5284 },
    },
    createdAt: '2026-02-07T12:00:00Z',
  },
  {
    id: 'usr_farmer_09',
    phoneNumber: '+919845009988',
    countryCode: 'IN',
    name: 'Manjunath Hegde',
    email: 'manjunath.hegde@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Sirsi, Uttara Kannada, Karnataka, India',
    farmSizeAcres: 15.5,
    primaryCrops: ['GI Sirsi Supari (Arecanut)', 'Coorg Arabica Shade-Grown Coffee', 'Bird Chilli'],
    certifications: ['ADITI-ORG-NPOP-0182', 'KA-AGRI-ORG-7703'],
    fpoName: 'Sahyadri Organic Spices & Plantation FPC',
    soilHealthCardId: 'SHC-KA-UTT-2025-04421',
    address: {
      village: 'Hulgol',
      gramPanchayat: 'Hulgol Gram Panchayat',
      tehsil: 'Sirsi',
      district: 'Uttara Kannada',
      state: 'Karnataka',
      pinCode: '581402',
      coordinates: { latitude: 14.6195, longitude: 74.8354 },
    },
    createdAt: '2026-02-08T15:30:00Z',
  },
  {
    id: 'usr_farmer_10',
    phoneNumber: '+919889223311',
    countryCode: 'IN',
    name: 'Ghulam Mohammad Dar',
    email: 'ghulam.dar@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Pampore, Pulwama, Jammu & Kashmir, India',
    farmSizeAcres: 4.8,
    primaryCrops: ['GI Kashmiri Mongra Saffron (Kesar)', 'Kashmiri Organic Walnuts', 'Almonds'],
    certifications: ['NPOP/NAB/0025/2025', 'JK-AGRI-ORG-1002'],
    fpoName: 'Pampore Valley Saffron Growers Co-operative Ltd.',
    soilHealthCardId: 'SHC-JK-PUL-2025-01019',
    address: {
      village: 'Ladoo',
      gramPanchayat: 'Pampore Karewa GP',
      tehsil: 'Pampore',
      district: 'Pulwama',
      state: 'Jammu & Kashmir',
      pinCode: '192121',
      coordinates: { latitude: 34.0167, longitude: 74.9333 },
    },
    createdAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'usr_farmer_11',
    phoneNumber: '+919866112288',
    countryCode: 'IN',
    name: 'Chennupati Subba Rao',
    email: 'chennupati.rao@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Guntur, Andhra Pradesh, India',
    farmSizeAcres: 19.0,
    primaryCrops: ['GI Guntur Sannam Organic Chilli', 'Turmeric', 'Organic Black Gram'],
    certifications: ['NPOP/NAB/0018/2025', 'AP-AGRI-ORG-4491'],
    fpoName: 'Guntur Organic Spices Consortium FPO',
    soilHealthCardId: 'SHC-AP-GUN-2025-08129',
    address: {
      village: 'Tadikonda',
      gramPanchayat: 'Tadikonda GP',
      tehsil: 'Tadikonda',
      district: 'Guntur',
      state: 'Andhra Pradesh',
      pinCode: '522236',
      coordinates: { latitude: 16.4250, longitude: 80.4500 },
    },
    createdAt: '2026-02-11T13:40:00Z',
  },
  {
    id: 'usr_farmer_12',
    phoneNumber: '+919854003322',
    countryCode: 'IN',
    name: 'Biren Kalita',
    email: 'biren.kalita@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Darrang, Assam, India',
    farmSizeAcres: 12.5,
    primaryCrops: ['GI Assam Black Rice (Chak-Hao)', 'Aromatic Joha Rice', 'Assam Orthodox Organic Tea'],
    certifications: ['NPOP/NAB/0034/2025', 'MOVCDNER-ASM-5501'],
    fpoName: 'Brahmaputra Organic Growers & Bio-Harvesters FPC',
    soilHealthCardId: 'SHC-AS-DAR-2025-03719',
    address: {
      village: 'Kharupetia',
      gramPanchayat: 'Kharupetia GP',
      tehsil: 'Mangaldai',
      district: 'Darrang',
      state: 'Assam',
      pinCode: '784115',
      coordinates: { latitude: 26.5167, longitude: 92.1333 },
    },
    createdAt: '2026-02-12T09:20:00Z',
  },
  {
    id: 'usr_farmer_13',
    phoneNumber: '+919816004455',
    countryCode: 'IN',
    name: 'Sanjeev Thakur',
    email: 'sanjeev.thakur@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Kangra, Himachal Pradesh, India',
    farmSizeAcres: 9.0,
    primaryCrops: ['GI Kangra Orthodox Green Tea', 'Himachal Organic Red Rice', 'Wild Pomegranate'],
    certifications: ['NPOP/NAB/0011/2025', 'HP-AGRI-ORG-2201'],
    fpoName: 'Dhauladhar Organic Agro Producer Company',
    soilHealthCardId: 'SHC-HP-KAN-2025-01994',
    address: {
      village: 'Palampur Rural',
      gramPanchayat: 'Palampur GP',
      tehsil: 'Palampur',
      district: 'Kangra',
      state: 'Himachal Pradesh',
      pinCode: '176061',
      coordinates: { latitude: 32.1109, longitude: 76.5363 },
    },
    createdAt: '2026-02-13T11:15:00Z',
  },
  {
    id: 'usr_farmer_14',
    phoneNumber: '+919871008899',
    countryCode: 'IN',
    name: 'Devendra Bhaskarrao Patil',
    email: 'devendra.patil@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Akola, Maharashtra, India',
    farmSizeAcres: 28.0,
    primaryCrops: ['Certified Organic Desi Long-Staple Cotton', 'Organic Pigeon Pea (Tur Dal)', 'Safflower'],
    certifications: ['NPOP/NAB/0019/2025', 'MH-AGRI-ORG-8841'],
    fpoName: 'Vidarbha Organic Cotton Growers Mahasangh',
    soilHealthCardId: 'SHC-MH-AKO-2025-06721',
    address: {
      village: 'Murtizapur Rural',
      gramPanchayat: 'Murtizapur GP',
      tehsil: 'Murtizapur',
      district: 'Akola',
      state: 'Maharashtra',
      pinCode: '444107',
      coordinates: { latitude: 20.7300, longitude: 77.3600 },
    },
    createdAt: '2026-02-14T14:00:00Z',
  },
  {
    id: 'usr_farmer_15',
    phoneNumber: '+919894002233',
    countryCode: 'IN',
    name: 'Murugan Palanisamy',
    email: 'murugan.palanisamy@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Erode, Tamil Nadu, India',
    farmSizeAcres: 16.0,
    primaryCrops: ['GI Erode Turmeric', 'Organic Small Onions (Shallots)', 'Moringa Oleifera Powder'],
    certifications: ['TNOCD-NPOP-0012', 'TN-AGRI-ORG-4410'],
    fpoName: 'Bhavani River Basin Organic Cultivators FPC',
    soilHealthCardId: 'SHC-TN-ERO-2025-05510',
    address: {
      village: 'Perundurai',
      gramPanchayat: 'Perundurai GP',
      tehsil: 'Perundurai',
      district: 'Erode',
      state: 'Tamil Nadu',
      pinCode: '638052',
      coordinates: { latitude: 11.2750, longitude: 77.5850 },
    },
    createdAt: '2026-02-15T08:30:00Z',
  },
  {
    id: 'usr_farmer_16',
    phoneNumber: '+919823115544',
    countryCode: 'IN',
    name: 'Prataprao Chavan',
    email: 'prataprao.chavan@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Sangli, Maharashtra, India',
    farmSizeAcres: 17.5,
    primaryCrops: ['Desi Khapli Wheat (Emmer)', 'Waigaon Turmeric', 'Organic Sugarcane Jaggery'],
    certifications: ['NPOP/NAB/0019/2025', 'MH-AGRI-ORG-3320'],
    fpoName: 'Krishna Valley Ancient Grains Producer Co.',
    soilHealthCardId: 'SHC-MH-SAN-2025-09141',
    address: {
      village: 'Walwa',
      gramPanchayat: 'Walwa Gram Panchayat',
      tehsil: 'Walwa',
      district: 'Sangli',
      state: 'Maharashtra',
      pinCode: '416313',
      coordinates: { latitude: 17.0345, longitude: 74.2210 },
    },
    createdAt: '2026-02-16T09:00:00Z',
  },
  {
    id: 'usr_farmer_17',
    phoneNumber: '+919849227766',
    countryCode: 'IN',
    name: 'C. K. Ramachandran',
    email: 'ck.ramachandran@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Palakkad, Kerala, India',
    farmSizeAcres: 12.0,
    primaryCrops: ['GI Navara Medicinal Rice', 'GI Palakkadan Matta Rice', 'Organic Coconut'],
    certifications: ['INDOCERT-NPOP-0041', 'KL-AGRI-ORG-7782'],
    fpoName: 'Nila Ayurvedic Heritage Paddy Conservers FPC',
    soilHealthCardId: 'SHC-KL-PAL-2025-04419',
    address: {
      village: 'Chittur',
      gramPanchayat: 'Chittur-Thathamangalam GP',
      tehsil: 'Chittur',
      district: 'Palakkad',
      state: 'Kerala',
      pinCode: '678101',
      coordinates: { latitude: 10.7020, longitude: 76.7190 },
    },
    createdAt: '2026-02-17T11:20:00Z',
  },
  {
    id: 'usr_farmer_18',
    phoneNumber: '+919835001199',
    countryCode: 'IN',
    name: 'Bikram Senapati',
    email: 'bikram.senapati@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Bastar, Chhattisgarh, India',
    farmSizeAcres: 8.0,
    primaryCrops: ['Organic Wild Forest Honey', 'Kodo-Kutki Millets', 'Mahuwa Flowers'],
    certifications: ['PGS-INDIA-ORG-CG-2025', 'NPOP/NAB/0031/2025'],
    fpoName: 'Dandakaranya Forest Bio-Treasures Cooperative',
    soilHealthCardId: 'SHC-CG-BAS-2025-01209',
    address: {
      village: 'Tokapal',
      gramPanchayat: 'Tokapal GP',
      tehsil: 'Tokapal',
      district: 'Bastar',
      state: 'Chhattisgarh',
      pinCode: '494001',
      coordinates: { latitude: 19.0700, longitude: 81.9600 },
    },
    createdAt: '2026-02-18T10:10:00Z',
  },
  {
    id: 'usr_farmer_19',
    phoneNumber: '+919832004488',
    countryCode: 'IN',
    name: 'Tashi Namgyal',
    email: 'tashi.namgyal@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'East Sikkim, Sikkim, India',
    farmSizeAcres: 5.5,
    primaryCrops: ['GI Sikkim Large Cardamom', 'Organic Ginger (Bhaise)', 'Dalle Khursani Chilli'],
    certifications: ['SSOCA-NPOP-0001', 'SIKKIM-100-ORG-2025'],
    fpoName: 'Himalayan 100% Organic Spices Cultivators Union',
    soilHealthCardId: 'SHC-SK-EAS-2025-00812',
    address: {
      village: 'Rongli',
      gramPanchayat: 'Rongli Gram Panchayat',
      tehsil: 'Rongli',
      district: 'Pakyong (East Sikkim)',
      state: 'Sikkim',
      pinCode: '737131',
      coordinates: { latitude: 27.2000, longitude: 88.7000 },
    },
    createdAt: '2026-02-19T14:40:00Z',
  },
  {
    id: 'usr_farmer_20',
    phoneNumber: '+919813009911',
    countryCode: 'IN',
    name: 'Devi Lal Gurjar',
    email: 'devilal.gurjar@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Bharatpur, Rajasthan, India',
    farmSizeAcres: 26.0,
    primaryCrops: ['Cold-Pressed Organic Mustard (Kachi Ghani)', 'Desi Wheat', 'Pearl Millet'],
    certifications: ['PGS-INDIA-ORG-RJ-9941', 'NPOP/NAB/0016/2025'],
    fpoName: 'Brajbhumi Organic Oilseeds & Grains Producers Union',
    soilHealthCardId: 'SHC-RJ-BHA-2025-04491',
    address: {
      village: 'Kumher Rural',
      gramPanchayat: 'Kumher GP',
      tehsil: 'Kumher',
      district: 'Bharatpur',
      state: 'Rajasthan',
      pinCode: '321201',
      coordinates: { latitude: 27.3167, longitude: 77.3667 },
    },
    createdAt: '2026-02-20T08:15:00Z',
  },
  {
    id: 'usr_consumer_01',
    phoneNumber: '+919811122233',
    countryCode: 'IN',
    name: 'Pooja Sharma',
    email: 'pooja.sharma@gmail.com',
    persona: 'consumer',
    roles: ['consumer', 'gardener'],
    verified: true,
    location: 'Mumbai, Maharashtra, India',
    gardenType: 'Urban Balcony & Terrace Garden',
    createdAt: '2026-02-10T11:20:00Z',
  },
  {
    id: 'usr_bulk_01',
    phoneNumber: '+919822334455',
    countryCode: 'IN',
    name: 'AgroFlour Milling Mills Corp',
    contactPerson: 'Vikram Mehta',
    email: 'procurement@agroflour.com',
    persona: 'bulkBuyer',
    roles: ['bulkBuyer'],
    verified: true,
    location: 'Pune Industrial Area, Maharashtra, India',
    gstNumber: '27AABCA1234F1Z5',
    escrowDepositBalance: 1500000,
    createdAt: '2026-01-05T09:30:00Z',
  },
  {
    id: 'usr_seller_01',
    phoneNumber: '+919833445566',
    countryCode: 'IN',
    name: 'GreenBio Earth Labs Inc.',
    contactPerson: 'Dr. Suresh Joshi',
    email: 'sales@greenbioearth.com',
    persona: 'seller',
    roles: ['seller'],
    verified: true,
    location: 'Ahmedabad, Gujarat, India',
    licenseNo: 'NPOP/NAB/0014/2025',
    labPurityRating: 99.8,
    createdAt: '2025-11-20T14:15:00Z',
  },
  {
    id: 'usr_expert_01',
    phoneNumber: '+919844556677',
    countryCode: 'IN',
    name: 'Dr. Anita Deshmukh',
    email: 'dr.anita@soilmicrobio.org',
    persona: 'expert',
    roles: ['expert'],
    verified: true,
    title: 'Senior Agronomist & Soil Microbiologist (PhD, IARI)',
    specializations: ['Soil Health', 'Microbial Inoculants', 'Organic Transition', 'Pest Biocontrol'],
    consultationRateINR: 1200,
    rating: 4.95,
    consultationsCompleted: 84,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    createdAt: '2025-10-01T10:00:00Z',
  },
  {
    id: 'usr_admin_01',
    phoneNumber: '+919855667788',
    countryCode: 'IN',
    name: 'Swadesh Compliance Admin',
    email: 'compliance@ecoswadesh.com',
    persona: 'admin',
    roles: ['admin', 'moderator'],
    verified: true,
    department: 'Trust, Certification & Regulatory Affairs',
    createdAt: '2025-09-01T08:00:00Z',
  },
];

const SEED_CERTIFICATIONS = [
  {
    id: 'cert-1',
    name: 'Jaivik Bharat / NPOP Organic',
    type: 'NATIONAL',
    country: 'India',
    issuingAuthority: 'APEDA Ministry of Commerce & Industry',
    licenseNo: 'NPOP/NAB/0014/2025',
    verifiedScore: 99,
    validUntil: '2028-12-31',
    badgeText: 'National Organic Standard',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-2',
    name: 'USDA Organic NOP Certified',
    type: 'INTERNATIONAL',
    country: 'United States / Global',
    issuingAuthority: 'USDA National Organic Program',
    licenseNo: 'USDA-NOP-884920-US',
    verifiedScore: 98,
    validUntil: '2027-09-30',
    badgeText: 'USDA Global Organic Standard',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-3',
    name: 'Maharashtra State Organic Board Seal',
    type: 'LOCAL_GOV',
    country: 'India (Maharashtra State)',
    issuingAuthority: 'State Department of Agriculture & Agro-Board',
    licenseNo: 'MH-AGRI-ORG-4402',
    verifiedScore: 96,
    validUntil: '2026-11-15',
    badgeText: 'Local Govt Approved',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-4',
    name: 'PGS-India Green (Conversion Phase)',
    type: 'NATIONAL',
    country: 'India',
    issuingAuthority: 'National Centre of Organic Farming (NCOF / MoA&FW)',
    licenseNo: 'PGS-INDIA-GRN-2025-091',
    verifiedScore: 95,
    validUntil: '2027-03-31',
    badgeText: 'PGS-India Green Conversion',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-5',
    name: 'PGS-India Organic (Full Certification)',
    type: 'NATIONAL',
    country: 'India',
    issuingAuthority: 'Ministry of Agriculture & Farmers Welfare, Govt of India',
    licenseNo: 'PGS-INDIA-ORG-2025-448',
    verifiedScore: 99,
    validUntil: '2028-06-30',
    badgeText: 'PGS-India Certified Organic',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-6',
    name: 'INDOCERT Organic Certification',
    type: 'NATIONAL',
    country: 'India (Kerala & South Zone)',
    issuingAuthority: 'Indian Organic Certification Agency (INDOCERT)',
    licenseNo: 'INDOCERT-NPOP-0041',
    verifiedScore: 98,
    validUntil: '2027-12-31',
    badgeText: 'INDOCERT NPOP Verified',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-7',
    name: 'Demeter Biodynamic Agriculture Seal',
    type: 'INTERNATIONAL',
    country: 'Global / Demeter India',
    issuingAuthority: 'Demeter International & Biodynamic Association of India',
    licenseNo: 'DEMETER-IND-99120',
    verifiedScore: 99.5,
    validUntil: '2028-10-31',
    badgeText: 'Demeter Biodynamic Certified',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-8',
    name: 'Tamil Nadu Organic Certification Department (TNOCD)',
    type: 'LOCAL_GOV',
    country: 'India (Tamil Nadu)',
    issuingAuthority: 'Directorate of Organic Certification, Govt of Tamil Nadu',
    licenseNo: 'TNOCD-NPOP-0012',
    verifiedScore: 97,
    validUntil: '2027-08-31',
    badgeText: 'TN State Govt Certified',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-9',
    name: 'Uttarakhand Organic Commodity Board (UOCB)',
    type: 'LOCAL_GOV',
    country: 'India (Uttarakhand)',
    issuingAuthority: 'Uttarakhand State Organic Agency',
    licenseNo: 'UK-UOCB-NPOP-5510',
    verifiedScore: 98,
    validUntil: '2028-04-30',
    badgeText: 'Himalayan Organic State Board',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-10',
    name: 'Sikkim 100% Organic State Standard (SSOCA)',
    type: 'LOCAL_GOV',
    country: 'India (Sikkim)',
    issuingAuthority: 'Sikkim State Organic Certification Agency',
    licenseNo: 'SSOCA-NPOP-0001',
    verifiedScore: 99.8,
    validUntil: '2029-01-31',
    badgeText: '100% Organic State Certified',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=100&auto=format&fit=crop&q=80',
  },
];

const SEED_PRODUCTS = [
  // ==========================================
  // CATEGORY 1: bulkHarvest (Grains, Millets, Pulses, GI Spices, Fruits, Tea/Coffee)
  // ==========================================
  {
    id: 'prod-1',
    name: 'Direct Farm Harvest: 100% Organic MP Sharbati Wheat',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_01',
    farmerName: 'Ramesh Patel',
    sellerId: 'usr_farmer_01',
    sellerName: 'Malwa Narmada Organic Farmers Producer Co. Ltd.',
    sellerType: 'Certified Organic Farmer Collective',
    origin: 'Sehore, Madhya Pradesh, India',
    rating: 4.95,
    reviewsCount: 148,
    certifiedType: 'NATIONAL',
    certName: 'Jaivik Bharat / NPOP Standard (APEDA)',
    certLicense: 'NPOP/NAB/0014/2025',
    labPurityRating: '100% Pesticide-Residue Free (0.00 ppm)',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80',
    retailPrice: 65,
    retailUnit: 'Kg',
    retailMinQty: 5,
    bulkAvailable: true,
    bulkPricePerTon: 42000,
    bulkMinTons: 5,
    bulkUnit: 'Ton',
    description: 'Golden, naturally sweet Sharbati wheat grown in the black soil plains of Sehore, MP. Cultivated using cow-dung Jeevamrutha and zero chemical synthetics.',
    moistureContent: '11.2% Max',
    grainPurity: '99.8%',
    inStock: true,
    stockQuantity: 120,
    createdAt: '2026-01-22T08:30:00Z',
  },
  {
    id: 'prod-2',
    name: 'Aromatic Himalayan Traditional Basmati 1121 Paddy (Long Grain)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_04',
    farmerName: 'Gurpreet Singh Dhillon',
    sellerId: 'usr_farmer_04',
    sellerName: 'Malwa Progressive Organic Growers Society',
    sellerType: 'Certified Organic Farmer Collective',
    origin: 'Bathinda, Punjab, India',
    rating: 4.92,
    reviewsCount: 112,
    certifiedType: 'NATIONAL',
    certName: 'APEDA NPOP & Punjab Organic Board',
    certLicense: 'NPOP/NAB/0009/2025',
    labPurityRating: 'Aflatoxin & Heavy Metal Free (NABL Tested)',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    retailPrice: 95,
    retailUnit: 'Kg',
    retailMinQty: 5,
    bulkAvailable: true,
    bulkPricePerTon: 72000,
    bulkMinTons: 4,
    bulkUnit: 'Ton',
    description: 'Extra-long grain 8.4mm aged Basmati rice cultivated along canal waters with green manure and Trichoderma biological seed dressing.',
    inStock: true,
    stockQuantity: 85,
    createdAt: '2026-01-28T10:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'GI Koraput Kalajeera Organic Rice (Prince of Rice)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_07',
    farmerName: 'Subhashree Mohapatra',
    sellerId: 'usr_farmer_07',
    sellerName: 'Sabari Tribal Organic Farmers Producer Collective',
    sellerType: 'Tribal Farmer Producer Cooperative',
    origin: 'Koraput, Odisha, India',
    rating: 4.98,
    reviewsCount: 76,
    certifiedType: 'NATIONAL',
    certName: 'PGS-India Organic & GI Tagged Heritage Rice',
    certLicense: 'PGS-INDIA-ORG-OD-4409',
    labPurityRating: '100% Heirloom Indigenous Grain',
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600&auto=format&fit=crop&q=80',
    retailPrice: 140,
    retailUnit: 'Kg',
    retailMinQty: 2,
    bulkAvailable: true,
    bulkPricePerTon: 98000,
    bulkMinTons: 2,
    bulkUnit: 'Ton',
    description: 'Famed scented black-husked aromatic rice grown by tribal farmers of Koraput valley. Rich in anthocyanins, iron, and dietary fiber.',
    inStock: true,
    stockQuantity: 40,
    createdAt: '2026-02-06T11:30:00Z',
  },
  {
    id: 'prod-4',
    name: 'GI Assam Black Rice (Chak-Hao / High Antioxidant Superfood)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_12',
    farmerName: 'Biren Kalita',
    sellerId: 'usr_farmer_12',
    sellerName: 'Brahmaputra Organic Growers & Bio-Harvesters FPC',
    sellerType: 'Organic Farmer Producer Company',
    origin: 'Darrang, Assam, India',
    rating: 4.94,
    reviewsCount: 64,
    certifiedType: 'NATIONAL',
    certName: 'MOVCDNER & Jaivik Bharat Certified',
    certLicense: 'MOVCDNER-ASM-5501',
    labPurityRating: 'Deep Purple Anthocyanin Density > 8.5mg/g',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&auto=format&fit=crop&q=80',
    retailPrice: 190,
    retailUnit: 'Kg',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 145000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Ancient medicinal black glutinous rice with intense nutty aroma and rich antioxidant properties. Grown chemical-free in Brahmaputra floodplains.',
    inStock: true,
    stockQuantity: 28,
    createdAt: '2026-02-12T10:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'High-Curcumin Lakadong Turmeric Whole & Ground (Curcumin > 7.5%)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_02',
    farmerName: 'Kongthong Synrem',
    sellerId: 'usr_farmer_02',
    sellerName: 'Jaintia Organic Spices Farmer Producer Company',
    sellerType: 'Women Led Tribal FPO',
    origin: 'West Jaintia Hills, Meghalaya, India',
    rating: 4.99,
    reviewsCount: 220,
    certifiedType: 'NATIONAL',
    certName: 'NPOP TraceNet & Meghalaya Organic Mission',
    certLicense: 'NPOP/NAB/0022/2025',
    labPurityRating: 'HPLC Certified 7.82% Curcumin Content',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80',
    retailPrice: 380,
    retailUnit: 'Kg',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 280000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'World-renowned highest curcumin turmeric grown in pristine high-altitude organic hills of Jaintia. Zero lead chromate, 100% pure sun-dried rhizomes.',
    inStock: true,
    stockQuantity: 35,
    createdAt: '2026-01-20T12:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'GI Kashmiri Mongra Grade-A1 Organic Saffron (Pure Stigmas)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_10',
    farmerName: 'Ghulam Mohammad Dar',
    sellerId: 'usr_farmer_10',
    sellerName: 'Pampore Valley Saffron Growers Co-operative Ltd.',
    sellerType: 'GI Certified Saffron Heritage Grower',
    origin: 'Pampore, Pulwama, Jammu & Kashmir, India',
    rating: 5.0,
    reviewsCount: 310,
    certifiedType: 'NATIONAL',
    certName: 'National Saffron Mission & APEDA NPOP',
    certLicense: 'NPOP/NAB/0025/2025',
    labPurityRating: 'ISO 3632 Crocin Color Strength > 240',
    image: 'https://images.unsplash.com/photo-1608797178974-15b35a61dd75?w=600&auto=format&fit=crop&q=80',
    retailPrice: 350,
    retailUnit: 'Gram (Pack of 1g)',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 240000000,
    bulkMinTons: 0.005,
    bulkUnit: 'Kg (Bulk Pack)',
    description: 'Pure hand-plucked deep crimson red Mongra saffron filaments grown in the Karewas of Pampore. Unmatched medicinal aroma, safranal and crocin strength.',
    inStock: true,
    stockQuantity: 1200,
    createdAt: '2026-02-10T11:00:00Z',
  },
  {
    id: 'prod-7',
    name: 'GI Malabar Bold Black Pepper & Tellicherry Garbled Extra Bold (TGSEB)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_06',
    farmerName: 'Thresiamma Mathew',
    sellerId: 'usr_farmer_06',
    sellerName: 'Wayanad Bio-Spices & Coffee Producers Union',
    sellerType: 'Certified Spices Cooperative',
    origin: 'Wayanad, Kerala, India',
    rating: 4.96,
    reviewsCount: 165,
    certifiedType: 'NATIONAL',
    certName: 'INDOCERT NPOP Organic & Spices Board India',
    certLicense: 'INDOCERT-NPOP-0041',
    labPurityRating: 'Piperine Content 6.4%, Moisture < 11%',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=600&auto=format&fit=crop&q=80',
    retailPrice: 620,
    retailUnit: 'Kg',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 490000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Direct harvest shade-grown bold black pepper vines thriving in bio-diverse tropical agro-forests of Western Ghats, Wayanad.',
    inStock: true,
    stockQuantity: 45,
    createdAt: '2026-02-04T10:30:00Z',
  },
  {
    id: 'prod-8',
    name: 'GI Ratnagiri Alphonso Mango (Hapus) - Export Grade A',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_03',
    farmerName: 'Mahadev Tukaram Jadhav',
    sellerId: 'usr_farmer_03',
    sellerName: 'Konkan Krishi Ratna Organic FPO',
    sellerType: 'Certified Fruit Growers Collective',
    origin: 'Ratnagiri, Maharashtra, India',
    rating: 4.97,
    reviewsCount: 290,
    certifiedType: 'LOCAL_GOV',
    certName: 'GI Tag No. 139 & Maharashtra Organic Seal',
    certLicense: 'MH-AGRI-ORG-5510',
    labPurityRating: 'Brix Sugar 19.5°, 100% Carbine-Free Ripening',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&auto=format&fit=crop&q=80',
    retailPrice: 1200,
    retailUnit: 'Dozen (12 Pcs Box)',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 180000,
    bulkMinTons: 1,
    bulkUnit: 'Ton (Crates)',
    description: 'Tree-ripened authentic Konkan Ratnagiri Alphonso mangoes with unmatched saffron pulp, sweet aroma, and zero chemical ethylene ripening.',
    inStock: true,
    stockQuantity: 15,
    createdAt: '2026-01-25T14:00:00Z',
  },
  {
    id: 'prod-9',
    name: 'Ancient Desi Khapli Wheat (Emmer / Low Glycemic Index & High Protein)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_16',
    farmerName: 'Prataprao Chavan',
    sellerId: 'usr_farmer_16',
    sellerName: 'Krishna Valley Ancient Grains Producer Co.',
    sellerType: 'Heirloom Grain Farmers Collective',
    origin: 'Sangli, Maharashtra, India',
    rating: 4.96,
    reviewsCount: 108,
    certifiedType: 'NATIONAL',
    certName: 'Jaivik Bharat / Maharashtra Organic Board',
    certLicense: 'MH-AGRI-ORG-3320',
    labPurityRating: '100% Unhybridized Heirloom Emmer Wheat',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80',
    retailPrice: 90,
    retailUnit: 'Kg',
    retailMinQty: 5,
    bulkAvailable: true,
    bulkPricePerTon: 68000,
    bulkMinTons: 3,
    bulkUnit: 'Ton',
    description: 'Traditional unhybridized Emmer wheat containing easily digestible gluten and high dietary fiber. Ideal for diabetic-friendly diets.',
    inStock: true,
    stockQuantity: 70,
    createdAt: '2026-02-16T10:00:00Z',
  },
  {
    id: 'prod-10',
    name: 'GI Navara Medicinal Ayurvedic Heritage Rice (Red Husked)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_17',
    farmerName: 'C. K. Ramachandran',
    sellerId: 'usr_farmer_17',
    sellerName: 'Nila Ayurvedic Heritage Paddy Conservers FPC',
    sellerType: 'Medicinal Paddy Cultivators Union',
    origin: 'Palakkad, Kerala, India',
    rating: 4.99,
    reviewsCount: 145,
    certifiedType: 'NATIONAL',
    certName: 'INDOCERT NPOP & GI Tag No. 34',
    certLicense: 'INDOCERT-NPOP-0041',
    labPurityRating: 'Rich in Polyphenols, Zinc & Iron (100% Pure)',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    retailPrice: 220,
    retailUnit: 'Kg',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 165000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: '2000-year-old medicinal rice used in Ayurvedic Panchakarma treatments. Strengthens immune resistance and muscle tissue regeneration.',
    inStock: true,
    stockQuantity: 22,
    createdAt: '2026-02-17T12:00:00Z',
  },
  {
    id: 'prod-11',
    name: 'Raw Unprocessed Bastar Wild Forest Honey (Multifloral Forest Flora)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_18',
    farmerName: 'Bikram Senapati',
    sellerId: 'usr_farmer_18',
    sellerName: 'Dandakaranya Forest Bio-Treasures Cooperative',
    sellerType: 'Tribal Honey Gatherers Union',
    origin: 'Bastar, Chhattisgarh, India',
    rating: 4.98,
    reviewsCount: 180,
    certifiedType: 'NATIONAL',
    certName: 'TRIFED Organic & PGS-India Certified',
    certLicense: 'PGS-INDIA-ORG-CG-2025',
    labPurityRating: 'Zero Sugar Adulteration / C4 Sugar Negative (NABL NMR Tested)',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80',
    retailPrice: 550,
    retailUnit: 'Kg (Glass Jar)',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 390000,
    bulkMinTons: 1,
    bulkUnit: 'Ton (Stainless Steel Drums)',
    description: 'Raw, unpasteurized forest honey gathered from wild Apis dorsata bee colonies in the deep forests of Bastar. Packed with live enzymes and natural pollen.',
    inStock: true,
    stockQuantity: 18,
    createdAt: '2026-02-18T11:00:00Z',
  },
  {
    id: 'prod-12',
    name: 'GI Sikkim Single-Origin Large Cardamom (Bara Elaichi)',
    category: 'bulkHarvest',
    farmerId: 'usr_farmer_19',
    farmerName: 'Tashi Namgyal',
    sellerId: 'usr_farmer_19',
    sellerName: 'Himalayan 100% Organic Spices Cultivators Union',
    sellerType: 'High Altitude Organic FPO',
    origin: 'East Sikkim, Sikkim, India',
    rating: 4.97,
    reviewsCount: 92,
    certifiedType: 'LOCAL_GOV',
    certName: 'SSOCA Sikkim 100% Organic State Certified',
    certLicense: 'SSOCA-NPOP-0001',
    labPurityRating: 'Cineole Content > 70% of Volatile Oil',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=600&auto=format&fit=crop&q=80',
    retailPrice: 1450,
    retailUnit: 'Kg',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 1150000,
    bulkMinTons: 0.5,
    bulkUnit: 'Ton',
    description: 'Smoky, bold dark purple cardamom pods dried over traditional Himalayan Bhatti curing kilns from Sikkim, the world’s first 100% organic state.',
    inStock: true,
    stockQuantity: 12,
    createdAt: '2026-02-19T15:00:00Z',
  },

  // ==========================================
  // CATEGORY 2: fertilizers (Bio-NPK, PROM, Humic Vermicompost, Seaweed, Potash, Inoculants)
  // ==========================================
  {
    id: 'prod-13',
    name: 'Bio-Active NPK Liquid Organic Fertilizer (Consortium)',
    category: 'fertilizers',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Gujarat, India',
    rating: 4.9,
    reviewsCount: 142,
    certifiedType: 'NATIONAL',
    certName: 'Jaivik Bharat & USDA Organic',
    certLicense: 'NPOP/NAB/0014/2025',
    labPurityRating: '99.4% Chemical-Free / Bacterial Count 1x10^9 CFU/ml',
    image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?w=600&auto=format&fit=crop&q=80',
    retailPrice: 450,
    retailUnit: 'Liter',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 85000,
    bulkMinTons: 2,
    bulkUnit: 'Ton',
    description: 'High-potency microbial nitrogen, phosphorus, and potassium liquid fertilizer. Enhances root mass by 40% and boosts soil organic carbon naturally.',
    npkRatio: 'N: 6% | P: 4% | K: 8%',
    usageDose: '5 ml per liter of irrigation water or 200 Liters per acre via drip.',
    inStock: true,
    stockQuantity: 4500,
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prod-14',
    name: 'Premium Vermicompost Soil Conditioner (Enriched with Humic Acid & Mycorrhiza)',
    category: 'fertilizers',
    farmerId: 'usr_farmer_01',
    farmerName: 'Ramesh Patel',
    sellerId: 'usr_farmer_01',
    sellerName: 'EarthWorm Gold Farmers Union',
    sellerType: 'Local Farmer Cooperative',
    origin: 'Madhya Pradesh, India',
    rating: 4.85,
    reviewsCount: 210,
    certifiedType: 'LOCAL_GOV',
    certName: 'MP State Organic Agriculture Council',
    certLicense: 'MP-AGRI-ORG-4402',
    labPurityRating: '100% Pure Worm Castings, C:N Ratio 14:1',
    image: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?w=600&auto=format&fit=crop&q=80',
    retailPrice: 25,
    retailUnit: 'Kg Bag',
    retailMinQty: 5,
    bulkAvailable: true,
    bulkPricePerTon: 12500,
    bulkMinTons: 3,
    bulkUnit: 'Ton',
    description: 'Rich dark humus created by Eisenia Fetida earthworms fed on cow dung and neem leaves. Loaded with beneficial mycorrhizae and humic substances.',
    inStock: true,
    stockQuantity: 80,
    createdAt: '2026-02-05T14:40:00Z',
  },
  {
    id: 'prod-15',
    name: 'PROM (Phosphate Rich Organic Manure - Rock Phosphate + Compost)',
    category: 'fertilizers',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Rajasthan, India',
    rating: 4.87,
    reviewsCount: 78,
    certifiedType: 'NATIONAL',
    certName: 'FCO Approved & Jaivik Bharat Certified',
    certLicense: 'NPOP/NAB/0014/2025',
    labPurityRating: 'Total P2O5 > 10.4%, Organic Carbon > 20%',
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23998?w=600&auto=format&fit=crop&q=80',
    retailPrice: 32,
    retailUnit: 'Kg',
    retailMinQty: 10,
    bulkAvailable: true,
    bulkPricePerTon: 18000,
    bulkMinTons: 2,
    bulkUnit: 'Ton',
    description: 'Organic replacement for synthetic DAP. High bioavailability slow-release phosphorus solubilized by organic acids in compost.',
    inStock: true,
    stockQuantity: 110,
    createdAt: '2026-02-09T10:00:00Z',
  },
  {
    id: 'prod-16',
    name: 'Pure Seaweed Extract Bio-Stimulant & Plant Growth Booster (Ascophyllum Nodosum)',
    category: 'fertilizers',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Tamil Nadu, India',
    rating: 4.93,
    reviewsCount: 115,
    certifiedType: 'NATIONAL',
    certName: 'ICAR-CMFRI Certified Organic Bio-Input',
    certLicense: 'NPOP/NAB/0014/2025',
    labPurityRating: 'Alginic Acid 18%, Mannitol 5%, Cytokinins Active',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    retailPrice: 680,
    retailUnit: 'Liter Bottle',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 195000,
    bulkMinTons: 1,
    bulkUnit: 'Ton (Barrels)',
    description: 'Concentrated marine kelp extract loaded with natural auxins, betaines, and 60+ trace minerals to trigger flower retention and fruit sizing.',
    inStock: true,
    stockQuantity: 320,
    createdAt: '2026-02-11T12:00:00Z',
  },
  {
    id: 'prod-17',
    name: 'Bio-Potash Organic Fertilizer (Molasses Fermented - Potash K2O 14.5%)',
    category: 'fertilizers',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Maharashtra, India',
    rating: 4.88,
    reviewsCount: 62,
    certifiedType: 'NATIONAL',
    certName: 'FCO Schedule-IV Certified Bio-Fertilizer',
    certLicense: 'FCO-BIO-POT-2025-08',
    labPurityRating: 'Water Soluble Potash 14.8% / Organic Carbon 16%',
    image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?w=600&auto=format&fit=crop&q=80',
    retailPrice: 38,
    retailUnit: 'Kg Bag',
    retailMinQty: 10,
    bulkAvailable: true,
    bulkPricePerTon: 22000,
    bulkMinTons: 3,
    bulkUnit: 'Ton',
    description: 'Eco-friendly non-chloride organic alternative to MOP. Improves grain filling, sugar development in fruits, and drought resistance.',
    inStock: true,
    stockQuantity: 95,
    createdAt: '2026-02-13T14:30:00Z',
  },
  {
    id: 'prod-18',
    name: 'VAM Endomycorrhiza Bio-Fertilizer (Root Extension Granules)',
    category: 'fertilizers',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Karnataka, India',
    rating: 4.95,
    reviewsCount: 89,
    certifiedType: 'NATIONAL',
    certName: 'Jaivik Bharat & NCOF Registered',
    certLicense: 'NCOF-BIO-VAM-2025',
    labPurityRating: 'Infectivity 100 IP/g (Glomus intraradices)',
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23998?w=600&auto=format&fit=crop&q=80',
    retailPrice: 180,
    retailUnit: 'Kg Pack',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 115000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Symbiotic root-colonizing mycorrhizal fungus that expands the effective root surface area by 100x, boosting water and zinc/phosphate absorption.',
    inStock: true,
    stockQuantity: 400,
    createdAt: '2026-02-15T09:00:00Z',
  },

  // ==========================================
  // CATEGORY 3: bioPesticides (Neem, Trichoderma, Pseudomonas, Beauveria, Bt, Kashayam, Traps)
  // ==========================================
  {
    id: 'prod-19',
    name: 'Neem-Shield Bio-Pesticide & Cold-Pressed Neem Oil (10,000 PPM Azadirachtin)',
    category: 'bioPesticides',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'NeemTech Organics Ltd.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Rajasthan, India',
    rating: 4.9,
    reviewsCount: 96,
    certifiedType: 'NATIONAL',
    certName: 'USDA NOP & EU Bio Standards',
    certLicense: 'USDA-NOP-884920-US',
    labPurityRating: '10,000 PPM Azadirachtin Pure Active',
    image: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=600&auto=format&fit=crop&q=80',
    retailPrice: 380,
    retailUnit: '500ml Bottle',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 110000,
    bulkMinTons: 1,
    bulkUnit: 'Ton (Barrel Pack)',
    description: 'Broad-spectrum botanical pesticide effective against caterpillars, aphids, thrips, and whiteflies. Safe for beneficial pollinators like honeybees.',
    inStock: true,
    stockQuantity: 1800,
    createdAt: '2026-02-01T12:00:00Z',
  },
  {
    id: 'prod-20',
    name: 'Trichoderma Viride 1.5% WP (Bio-Fungicide for Root Rot & Wilt)',
    category: 'bioPesticides',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Control Lab',
    origin: 'Maharashtra, India',
    rating: 4.92,
    reviewsCount: 104,
    certifiedType: 'NATIONAL',
    certName: 'CIB&RC Registered & Jaivik Bharat',
    certLicense: 'CIBRC-BIO-2025-881',
    labPurityRating: 'Spore Count 2x10^6 CFU/g Min',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    retailPrice: 220,
    retailUnit: 'Kg Pack',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 140000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Antagonistic bio-control fungus that prevents Fusarium wilt, Rhizoctonia root rot, and damping-off across pulses, cotton, and vegetables.',
    inStock: true,
    stockQuantity: 650,
    createdAt: '2026-02-06T15:00:00Z',
  },
  {
    id: 'prod-21',
    name: 'Pseudomonas Fluorescens 1.0% WP (Bio-Bactericide & Plant Growth Promoter)',
    category: 'bioPesticides',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Control Lab',
    origin: 'Gujarat, India',
    rating: 4.89,
    reviewsCount: 87,
    certifiedType: 'NATIONAL',
    certName: 'CIB&RC Registered Bio-Input',
    certLicense: 'CIBRC-BIO-2025-904',
    labPurityRating: 'CFU Count 1x10^8 per gram',
    image: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600&auto=format&fit=crop&q=80',
    retailPrice: 240,
    retailUnit: 'Kg Pack',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 155000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Produces phenazine antibiotics and siderophores that suppress bacterial leaf blight, sheath rot, and downy mildew naturally.',
    inStock: true,
    stockQuantity: 420,
    createdAt: '2026-02-08T16:00:00Z',
  },
  {
    id: 'prod-22',
    name: 'Beauveria Bassiana 1.15% WP (Entomopathogenic Bio-Insecticide)',
    category: 'bioPesticides',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Bio-Control Lab',
    origin: 'Karnataka, India',
    rating: 4.94,
    reviewsCount: 73,
    certifiedType: 'NATIONAL',
    certName: 'CIB&RC Registered & NPOP Approved',
    certLicense: 'CIBRC-BIO-2025-912',
    labPurityRating: 'Spore Viability 1x10^8 CFU/g',
    image: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=600&auto=format&fit=crop&q=80',
    retailPrice: 290,
    retailUnit: 'Kg Pack',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 175000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'White muscardine entomopathogenic fungus that parasitizes bollworms, thrips, whiteflies, and diamondback moths through cuticle penetration.',
    inStock: true,
    stockQuantity: 380,
    createdAt: '2026-02-12T11:00:00Z',
  },
  {
    id: 'prod-23',
    name: 'Dashaparni Organic Botanical Herbal Extract (10-Leaf Kashayam Pest Repellent)',
    category: 'bioPesticides',
    farmerId: 'usr_farmer_01',
    farmerName: 'Ramesh Patel',
    sellerId: 'usr_farmer_01',
    sellerName: 'Malwa Narmada Organic Farmers Producer Co. Ltd.',
    sellerType: 'Farmer Producer Collective',
    origin: 'Madhya Pradesh, India',
    rating: 4.96,
    reviewsCount: 110,
    certifiedType: 'NATIONAL',
    certName: 'PGS-India Verified Herbal Formulation',
    certLicense: 'PGS-INDIA-ORG-2025-448',
    labPurityRating: '100% Botanical Ferment (Neem, Karanj, Calotropis, Castor)',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    retailPrice: 320,
    retailUnit: '1 Liter Bottle',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 95000,
    bulkMinTons: 1,
    bulkUnit: 'Ton (Barrels)',
    description: 'Vedic 10-leaf fermented bio-pesticide concoction that acts as a natural antifeedant, oviposition deterrent, and insect repellent.',
    inStock: true,
    stockQuantity: 500,
    createdAt: '2026-02-14T09:30:00Z',
  },

  // ==========================================
  // CATEGORY 4: seeds (Heirloom, Non-GMO, Grains, Vegetables, Cotton, Millets)
  // ==========================================
  {
    id: 'prod-24',
    name: 'High-Yield Hybrid Organic Tomato Seeds (F1 Wilt & TYLCV Resistant)',
    category: 'seeds',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'Vedic Seed Innovations',
    sellerType: 'Seed Breeder & Nursery',
    origin: 'Karnataka, India',
    rating: 4.9,
    reviewsCount: 175,
    certifiedType: 'NATIONAL',
    certName: 'National Seed Certification Board (NSCB)',
    certLicense: 'NSCB-IND-99120',
    labPurityRating: '98% Germination Guaranteed / Genetic Purity 99.5%',
    image: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&auto=format&fit=crop&q=80',
    retailPrice: 220,
    retailUnit: '10g Packet',
    retailMinQty: 1,
    bulkAvailable: false,
    description: 'High-yielding semi-determinate tomato seeds bred for bacterial wilt resistance, firmness, and rich lycopene flavor.',
    inStock: true,
    stockQuantity: 500,
    createdAt: '2026-02-12T09:10:00Z',
  },
  {
    id: 'prod-25',
    name: 'Indigenous Desi Cotton Seeds (Suvin & Karunganni Heritage Varieties)',
    category: 'seeds',
    farmerId: 'usr_farmer_14',
    farmerName: 'Devendra Bhaskarrao Patil',
    sellerId: 'usr_farmer_14',
    sellerName: 'Vidarbha Organic Cotton Growers Mahasangh',
    sellerType: 'Indigenous Seed Conservers Collective',
    origin: 'Maharashtra, India',
    rating: 4.94,
    reviewsCount: 65,
    certifiedType: 'NATIONAL',
    certName: 'National Bureau of Plant Genetic Resources (NBPGR)',
    certLicense: 'NBPGR-IND-DESI-2025',
    labPurityRating: '100% Non-GMO Heritage Variety Germination 92%',
    image: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=600&auto=format&fit=crop&q=80',
    retailPrice: 450,
    retailUnit: '500g Packet',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 350000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Drought-tolerant heirloom Indian desi cotton seeds. Naturally resistant to bollworm without chemical sprays.',
    inStock: true,
    stockQuantity: 180,
    createdAt: '2026-02-14T11:00:00Z',
  },
  {
    id: 'prod-26',
    name: 'Organic Finger Millet (Ragi GPU-28 Certified Drought-Hardy Seeds)',
    category: 'seeds',
    farmerId: 'usr_farmer_07',
    farmerName: 'Subhashree Mohapatra',
    sellerId: 'usr_farmer_07',
    sellerName: 'Sabari Tribal Organic Farmers Producer Collective',
    sellerType: 'Indigenous Seed Bank Cooperative',
    origin: 'Odisha, India',
    rating: 4.92,
    reviewsCount: 88,
    certifiedType: 'NATIONAL',
    certName: 'ICAR-IIMR Millet Certified Variety',
    certLicense: 'ICAR-IIMR-RAGI-2025',
    labPurityRating: 'Germination Rate 96%, Moisture 10%',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    retailPrice: 160,
    retailUnit: '1 Kg Packet',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 85000,
    bulkMinTons: 1,
    bulkUnit: 'Ton',
    description: 'Short-duration, blast-tolerant traditional finger millet seeds with exceptional calcium and dietary fiber yielding capacity.',
    inStock: true,
    stockQuantity: 240,
    createdAt: '2026-02-16T14:00:00Z',
  },
  {
    id: 'prod-27',
    name: 'Heirloom Mattu Gulla GI Brinjal Seeds (Traditional Green Striped Eggplant)',
    category: 'seeds',
    farmerId: 'usr_farmer_09',
    farmerName: 'Manjunath Hegde',
    sellerId: 'usr_farmer_09',
    sellerName: 'Sahyadri Organic Spices & Plantation FPC',
    sellerType: 'Heirloom Seed Conservers',
    origin: 'Karnataka, India',
    rating: 4.97,
    reviewsCount: 54,
    certifiedType: 'NATIONAL',
    certName: 'GI Tag Heritage Seed Registry',
    certLicense: 'GI-SEED-MATTU-2025',
    labPurityRating: '100% Pure Mattu Gulla Heirloom Strain',
    image: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&auto=format&fit=crop&q=80',
    retailPrice: 180,
    retailUnit: '25g Packet',
    retailMinQty: 1,
    bulkAvailable: false,
    description: 'Famed 400-year-old GI-tagged light green striped spherical brinjal seeds known for tender texture and delicate sweet flavor.',
    inStock: true,
    stockQuantity: 150,
    createdAt: '2026-02-17T10:30:00Z',
  },

  // ==========================================
  // CATEGORY 5: equipment (Solar Pumps, Soil Scanners, Shredders, Traps, Drones)
  // ==========================================
  {
    id: 'prod-28',
    name: 'Solar-Powered Automated Drip Irrigation Kit (1 Acre Complete Set)',
    category: 'equipment',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'SunAgro Tech Systems',
    sellerType: 'Equipment Supplier',
    origin: 'Maharashtra, India',
    rating: 4.85,
    reviewsCount: 54,
    certifiedType: 'NATIONAL',
    certName: 'Bureau of Indian Standards (BIS Certified)',
    certLicense: 'BIS-AGRI-44120',
    labPurityRating: 'ISO 9001:2025 Quality Passed',
    image: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=600&auto=format&fit=crop&q=80',
    retailPrice: 24500,
    retailUnit: 'Full Kit (1 Acre)',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 215000,
    bulkMinTons: 1,
    bulkUnit: 'Set of 10 Acres',
    description: 'Complete water-saving precision drip irrigation system with automatic solar timer pump. Reduces water usage by up to 60%.',
    inStock: true,
    stockQuantity: 40,
    createdAt: '2026-02-15T16:20:00Z',
  },
  {
    id: 'prod-29',
    name: 'Handheld Mobile Digital Soil NPK & pH Spectrometer',
    category: 'equipment',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'AgroSensor Photonics Labs',
    sellerType: 'Precision Agri-Tech Manufacturer',
    origin: 'Karnataka, India',
    rating: 4.96,
    reviewsCount: 39,
    certifiedType: 'NATIONAL',
    certName: 'ICAR-IARI Calibrated & CE Certified',
    certLicense: 'ICAR-AGRI-TECH-2025-081',
    labPurityRating: '98.5% Correlation with NABL Wet Lab Tests',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    retailPrice: 18500,
    retailUnit: '1 Device Kit',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 160000,
    bulkMinTons: 1,
    bulkUnit: 'Box of 10 Units',
    description: 'Instant 45-second optical soil health testing scanner. Syncs via Bluetooth to the Eco Swadesh app for automated dosage generation.',
    inStock: true,
    stockQuantity: 65,
    createdAt: '2026-02-16T12:00:00Z',
  },
  {
    id: 'prod-30',
    name: 'Electric Bio-Waste Shredder & Compost Chaff Cutter (3 HP Motor)',
    category: 'equipment',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'SunAgro Tech Systems',
    sellerType: 'Agri-Machinery Manufacturer',
    origin: 'Punjab, India',
    rating: 4.91,
    reviewsCount: 42,
    certifiedType: 'NATIONAL',
    certName: 'Govt FMTTI Certified Agri Machinery',
    certLicense: 'FMTTI-SHREDDER-2025-44',
    labPurityRating: 'Heavy-Duty Carbon Steel Blades (Shred Rate 500 Kg/Hr)',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    retailPrice: 32000,
    retailUnit: '1 Unit Machine',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 280000,
    bulkMinTons: 1,
    bulkUnit: 'Set of 10 Units',
    description: 'High-speed organic residue and crop-straw shredder for preparing fast vermicompost feeding beds and biochar raw material.',
    inStock: true,
    stockQuantity: 25,
    createdAt: '2026-02-17T15:00:00Z',
  },
  {
    id: 'prod-31',
    name: 'Solar-Powered Automatic LED Insect Light Trap (1 Acre Pest Protection)',
    category: 'equipment',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'AgroSensor Photonics Labs',
    sellerType: 'Solar Pest Solutions',
    origin: 'Gujarat, India',
    rating: 4.88,
    reviewsCount: 61,
    certifiedType: 'NATIONAL',
    certName: 'National Organic Input Verification Board',
    certLicense: 'NOIVB-SOLAR-2025',
    labPurityRating: 'Auto Dusk-to-Dawn Optical Sensor (Pest Catch Range 1 Acre)',
    image: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=600&auto=format&fit=crop&q=80',
    retailPrice: 4200,
    retailUnit: '1 Unit Trap Kit',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 360000,
    bulkMinTons: 1,
    bulkUnit: 'Lot of 100 Traps',
    description: 'Chemical-free biological pest management light trap with automated solar panel and high-voltage grid funnel. Attracts and eliminates nocturnal moths.',
    inStock: true,
    stockQuantity: 110,
    createdAt: '2026-02-18T16:00:00Z',
  },
  {
    id: 'prod-32',
    name: 'Autonomous Agricultural Drone Bio-Sprayer (16-Liter Tank with Dual Radar)',
    category: 'equipment',
    farmerId: null,
    sellerId: 'usr_seller_01',
    sellerName: 'SunAgro Tech Systems',
    sellerType: 'Precision Aero-Tech Systems',
    origin: 'Telangana, India',
    rating: 4.98,
    reviewsCount: 28,
    certifiedType: 'NATIONAL',
    certName: 'DGCA Type Certified Agriculture Drone',
    certLicense: 'DGCA-AGRI-DRONE-2025-019',
    labPurityRating: 'Precision Spray Droplet Size 100-250 Microns',
    image: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=600&auto=format&fit=crop&q=80',
    retailPrice: 480000,
    retailUnit: 'Complete Drone & 3 Battery Pack',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 4400000,
    bulkMinTons: 1,
    bulkUnit: 'Fleet of 10 Drones',
    description: 'DGCA-certified drone engineered specifically for spraying microbial bio-fertilizers, neem extracts, and Trichoderma solutions over 25 acres per day.',
    inStock: true,
    stockQuantity: 15,
    createdAt: '2026-02-19T10:00:00Z',
  },
];

const SEED_COMMODITY_PRICES = [
  { crop: 'Organic Wheat (MP Sharbati - Sehore)', priceRetail: '₹65 / Kg', priceBulk: '₹42,000 / Ton', change: '+2.4%', trend: 'up', mandiBenchmark: '₹41,200 / Ton' },
  { crop: 'Organic Basmati Paddy Rice (1121)', priceRetail: '₹95 / Kg', priceBulk: '₹72,000 / Ton', change: '+3.1%', trend: 'up', mandiBenchmark: '₹69,500 / Ton' },
  { crop: 'Ancient Desi Khapli Wheat (Emmer)', priceRetail: '₹90 / Kg', priceBulk: '₹68,000 / Ton', change: '+1.9%', trend: 'up', mandiBenchmark: '₹66,000 / Ton' },
  { crop: 'Lakadong Turmeric (Jaintia Hills)', priceRetail: '₹380 / Kg', priceBulk: '₹280,000 / Ton', change: '+4.5%', trend: 'up', mandiBenchmark: '₹270,000 / Ton' },
  { crop: 'Malabar Black Pepper (Wayanad)', priceRetail: '₹620 / Kg', priceBulk: '₹490,000 / Ton', change: '+1.8%', trend: 'up', mandiBenchmark: '₹480,000 / Ton' },
  { crop: 'Alphonso Mango (Ratnagiri Hapus)', priceRetail: '₹1,200 / Doz', priceBulk: '₹180,000 / Ton', change: '+5.2%', trend: 'up', mandiBenchmark: '₹172,000 / Ton' },
  { crop: 'Koraput Kalajeera Heritage Rice', priceRetail: '₹140 / Kg', priceBulk: '₹98,000 / Ton', change: '+0.5%', trend: 'stable', mandiBenchmark: '₹96,000 / Ton' },
  { crop: 'Kashmiri Mongra Saffron (Pampore)', priceRetail: '₹350 / Gram', priceBulk: '₹240,000 / Kg', change: '+1.2%', trend: 'up', mandiBenchmark: '₹235,000 / Kg' },
  { crop: 'GI Navara Medicinal Rice (Kerala)', priceRetail: '₹220 / Kg', priceBulk: '₹165,000 / Ton', change: '+2.0%', trend: 'up', mandiBenchmark: '₹160,000 / Ton' },
  { crop: 'Bastar Wild Forest Honey', priceRetail: '₹550 / Kg', priceBulk: '₹390,000 / Ton', change: '+0.8%', trend: 'up', mandiBenchmark: '₹385,000 / Ton' },
  { crop: 'Sikkim Large Cardamom (Bara Elaichi)', priceRetail: '₹1,450 / Kg', priceBulk: '₹1,150,000 / Ton', change: '+3.4%', trend: 'up', mandiBenchmark: '₹1,120,000 / Ton' },
  { crop: 'Organic Desi Raw Cotton (Vidarbha)', priceRetail: '₹120 / Kg', priceBulk: '₹88,000 / Ton', change: '-1.1%', trend: 'down', mandiBenchmark: '₹86,500 / Ton' },
  { crop: 'Bio-NPK Liquid Fertilizer Consortium', priceRetail: '₹450 / Liter', priceBulk: '₹85,000 / Ton', change: '-0.8%', trend: 'down', mandiBenchmark: '₹88,000 / Ton' },
  { crop: 'Organic Vermicompost Humic Plus', priceRetail: '₹25 / Kg', priceBulk: '₹12,500 / Ton', change: '+1.5%', trend: 'up', mandiBenchmark: '₹12,000 / Ton' },
  { crop: 'Cold-Pressed Neem Oil (10,000 PPM)', priceRetail: '₹380 / 500ml', priceBulk: '₹110,000 / Ton', change: '0.0%', trend: 'stable', mandiBenchmark: '₹112,000 / Ton' },
];

const SEED_ORDERS = [
  {
    id: 'ORD-2026-9041',
    buyerId: 'usr_bulk_01',
    buyerName: 'AgroFlour Milling Mills Corp',
    sellerId: 'usr_farmer_01',
    sellerName: 'Malwa Narmada Organic Farmers Producer Co. Ltd.',
    logisticsType: 'HEAVY_FREIGHT',
    shippingAddress: 'Central Warehouse, Plot 14, Pune Industrial Area, Maharashtra, IN',
    currency: 'INR',
    items: [
      {
        productId: 'prod-1',
        productName: 'Direct Farm Harvest: 100% Organic MP Sharbati Wheat',
        isBulk: true,
        quantity: 10,
        unit: 'Ton',
        unitPrice: 42000,
        total: 420000,
        certificationSnapshot: {
          certName: 'Jaivik Bharat / NPOP Standard (APEDA)',
          certLicense: 'NPOP/NAB/0014/2025',
          verifiedScore: 99,
        },
      },
    ],
    subtotal: 420000,
    freightCharges: 4500,
    platformFeePct: 0.5,
    platformFee: 2100,
    grandTotal: 426600,
    escrowContractId: 'ESC-9041',
    escrowStatus: 'HELD_IN_ESCROW_POOL',
    paymentStatus: 'PAID_TO_ESCROW',
    paymentMethod: 'RAZORPAY_ROUTE_ESCROW',
    destinationLabInspectionStatus: 'PENDING_ARRIVAL',
    createdAt: '2026-07-24T06:30:00Z',
    shipmentId: 'SHIP-8921',
  },
  {
    id: 'ORD-2026-4402',
    buyerId: 'usr_consumer_01',
    buyerName: 'Pooja Sharma',
    sellerId: 'usr_seller_01',
    sellerName: 'GreenBio Earth Labs Inc.',
    logisticsType: 'RETAIL_PARCEL',
    shippingAddress: 'Flat 402, Sunshine Heights, Bandra West, Mumbai, IN',
    currency: 'INR',
    items: [
      {
        productId: 'prod-13',
        productName: 'Bio-Active NPK Liquid Organic Fertilizer',
        isBulk: false,
        quantity: 2,
        unit: 'Liter',
        unitPrice: 450,
        total: 900,
        certificationSnapshot: {
          certName: 'Jaivik Bharat & USDA Organic',
          certLicense: 'NPOP/NAB/0014/2025',
          verifiedScore: 99,
        },
      },
    ],
    subtotal: 900,
    freightCharges: 60,
    platformFee: 0,
    grandTotal: 960,
    escrowContractId: 'ESC-4402',
    escrowStatus: 'RELEASED_TO_SELLER',
    paymentStatus: 'PAID_SETTLED',
    paymentMethod: 'UPI_DIRECT',
    createdAt: '2026-07-23T14:15:00Z',
    shipmentId: 'SHIP-4402',
  },
];

const SEED_SHIPMENTS = [
  {
    id: 'SHIP-8921',
    orderId: 'ORD-2026-9041',
    type: 'BULK_FREIGHT',
    title: '15 Tons Organic Sharbati Wheat Truckload',
    origin: 'Farm #4, Barkheda Hasan, Sehore, MP',
    destination: 'AgroProcessor Flour Mill Warehouse, Pune, MH',
    weight: '15.0 Tons',
    carrier: 'EcoFreight Heavy Trucking Direct',
    status: 'IN_TRANSIT',
    driverName: 'Ramesh Singh',
    driverPhone: '+91 98230 11200',
    vehicleNo: 'MH-12-VT-9921',
    estDelivery: 'Tomorrow, 04:30 PM',
    escrowStatus: '₹6,30,000 Held in Escrow (Release after destination lab check)',
    telemetry: {
      temperatureCelsius: 24.2,
      humidityPct: 58.0,
      cargoMoisturePct: 11.2,
      gpsLatitude: 19.8762,
      gpsLongitude: 75.3433,
      speedKmh: 54,
      lastUpdated: new Date().toISOString(),
    },
    milestones: [
      { label: 'Harvest Loaded at Farm (Sehore)', date: '24 Jul, 08:00 AM', completed: true, timestamp: '2026-07-24T08:00:00Z' },
      { label: 'Weighbridge & Initial APEDA Seal Check', date: '24 Jul, 11:30 AM', completed: true, timestamp: '2026-07-24T11:30:00Z' },
      { label: 'En-Route on Highway NH-52', date: '24 Jul, 04:00 PM', completed: true, timestamp: '2026-07-24T16:00:00Z' },
      { label: 'Destination Lab Check at Warehouse', date: '25 Jul, 02:00 PM', completed: false },
      { label: 'Final Escrow Release to Farmer Bank Account', date: '25 Jul, 05:00 PM', completed: false },
    ],
  },
  {
    id: 'SHIP-4402',
    orderId: 'ORD-2026-4402',
    type: 'RETAIL_PARCEL',
    title: '5 Liters Bio-NPK Liquid & 2 Kg Vermicompost',
    origin: 'GreenBio Earth Depot, Ahmedabad, GJ',
    destination: 'Sunshine Heights, Bandra West, Mumbai, MH',
    weight: '7.2 Kg',
    carrier: 'GreenParcel Carbon-Neutral Courier',
    status: 'DISPATCHED',
    trackingNo: 'GP-992018442-IN',
    estDelivery: '26 Jul, 02:00 PM',
    escrowStatus: 'Payment Completed via UPI',
    telemetry: {
      temperatureCelsius: 22.0,
      humidityPct: 50.0,
      lastUpdated: new Date().toISOString(),
    },
    milestones: [
      { label: 'Order Confirmed', date: '23 Jul, 02:15 PM', completed: true },
      { label: 'Lab Sealed & Packaged with Anti-Counterfeit QR', date: '24 Jul, 09:00 AM', completed: true },
      { label: 'Dispatched via GreenParcel Express', date: '24 Jul, 01:00 PM', completed: true },
      { label: 'Out for Last-Mile Delivery', date: '26 Jul, 09:00 AM', completed: false },
    ],
  },
];

const SEED_COMMUNITY_POSTS = [
  {
    id: 'post-1',
    author: 'Dr. Anita Deshmukh',
    role: 'EXPERT',
    verifiedExpert: true,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    title: 'How to transition 5 acres from chemical farming to 100% Certified Organic without yield drop',
    content: 'Transitioning requires a 3-phase soil rejuvenation strategy. Start with bio-char and vermicompost to reseed beneficial mycorrhizae bacteria before cutting synthetic nitrogen. Within 120 days, soil organic carbon rises by 0.4% which stabilizes yields.',
    tags: ['Soil Health', 'Organic Transition', 'Bio-Fertilizers'],
    upvotes: 246,
    repliesCount: 38,
    date: '2 hours ago',
    createdAt: '2026-08-08T12:00:00Z',
  },
  {
    id: 'post-2',
    author: 'Gurpreet Singh Dhillon',
    role: 'FARMER',
    verifiedExpert: false,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    title: 'Direct Bulk Sales Experience: Bypassing Mandi Middlemen for 18 Tons of Basmati Paddy',
    content: 'Used Eco Swadesh Direct Freight last week to supply 18 Tons of organic basmati directly to a Pune flour mill. Escrow payment was released within 2 hours of lab test at warehouse! Received ₹72,000/Ton instead of ₹52,000 at local mandi.',
    tags: ['Direct Bulk Trade', 'Zero Middlemen', 'Escrow Payment', 'Basmati Rice'],
    upvotes: 189,
    repliesCount: 24,
    date: '5 hours ago',
    createdAt: '2026-08-08T09:30:00Z',
  },
  {
    id: 'post-3',
    author: 'Kongthong Synrem',
    role: 'FARMER',
    verifiedExpert: false,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    title: 'Lakadong Turmeric Cooperative Export Story: From Jaintia Hills to Global B2B Buyers',
    content: 'Through our FPO and Eco Swadesh APEDA digital verification, 120 tribal women farmers successfully dispatched 8 Tons of 7.8% curcumin turmeric rhizomes at guaranteed premium pricing under smart escrow contract.',
    tags: ['Lakadong Turmeric', 'Tribal Women FPO', 'APEDA NPOP Export', 'Fair Trade'],
    upvotes: 312,
    repliesCount: 45,
    date: '1 day ago',
    createdAt: '2026-08-07T14:20:00Z',
  },
  {
    id: 'post-4',
    author: 'Prataprao Chavan',
    role: 'FARMER',
    verifiedExpert: false,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    title: 'Reviving Ancient Khapli Wheat: High Market Demand & Zero Chemical Input Experience',
    content: 'Our Sangli collective transitioned 45 acres to indigenous Khapli (Emmer) wheat. Because Khapli has natural resistance to rust and pests, input costs dropped by 70%, while bulk buyers offered ₹68,000/Ton compared to ₹26,000 for hybrid wheat.',
    tags: ['Ancient Grains', 'Khapli Wheat', 'Low Glycemic', 'Farmer Profits'],
    upvotes: 278,
    repliesCount: 31,
    date: '2 days ago',
    createdAt: '2026-08-06T16:00:00Z',
  },
];

const SEED_AI_DIAGNOSES = [
  {
    id: 'diag-1',
    cropName: 'Tomato Plant (Solanum lycopersicum)',
    detectedDisease: 'Early Bacterial Leaf Blight (Alternaria solani)',
    confidence: '96.8% Accuracy',
    confidenceScore: 0.968,
    severity: 'Moderate Infection',
    organicRecipes: [
      'Spray 5ml/L Cold-Pressed Neem Oil (10,000 PPM) with 2g/L Baking Soda solution every 5 days.',
      'Apply Trichoderma viride bio-fungicide during early morning hours to colonize leaf surface.',
      'Prune lower infected yellow leaves and burn them away from field to prevent airborne spore propagation.',
    ],
    recommendedFertilizer: 'Bio-Active Potassium & Seaweed Extract for natural plant systemic resistance.',
  },
  {
    id: 'diag-2',
    cropName: 'Cotton (Gossypium)',
    detectedDisease: 'Bacterial Blight & Whitefly Nymph Cluster',
    confidence: '94.2% Accuracy',
    confidenceScore: 0.942,
    severity: 'Early Warning',
    organicRecipes: [
      'Apply 5% Neem Seed Kernel Extract (NSKE) spray at sunset.',
      'Install 15 yellow sticky traps per acre at crop canopy height.',
      'Release Chrysoperla carnea green lacewing predatory larvae for biological whitefly control.',
    ],
    recommendedFertilizer: 'Bio-NPK Liquid foliar spray at 4ml/Liter water.',
  },
  {
    id: 'diag-3',
    cropName: 'Turmeric Plant (Curcuma longa)',
    detectedDisease: 'Rhizome Rot (Pythium aphanidermatum)',
    confidence: '95.4% Accuracy',
    confidenceScore: 0.954,
    severity: 'Moderate Hazard',
    organicRecipes: [
      'Drench root rhizosphere with Trichoderma viride & Pseudomonas fluorescens @ 10g/Litre water.',
      'Improve soil drainage to prevent standing water in planting beds.',
      'Dust bed with organic Neem Seed Cake powder @ 200 Kg/acre.',
    ],
    recommendedFertilizer: 'Humic-Enriched Vermicompost with bio-potash.',
  },
];

const SEED_DISPUTES = [
  {
    id: 'disp-901',
    orderId: 'ORD-2026-8802',
    buyerId: 'usr_bulk_01',
    sellerId: 'usr_farmer_01',
    productName: 'Organic Basmati Paddy Rice 20 Tons',
    claimType: 'Moisture Level Exceeds Contract Specification (14.2% vs 12.0% Max)',
    disputeAmountINR: 1440000,
    escrowStatus: 'FROZEN_PENDING_RETEST',
    independentLab: 'NABL Accredited AgriQuality Lab, Indore',
    sampleBatchId: 'BATCH-2026-NPOP-4421',
    status: 'SAMPLE_IN_TRANSIT_TO_LAB',
    timeline: [
      { step: 'Buyer Lodged Dispute at Destination Lab', timestamp: '2026-08-01T10:00:00Z', completed: true },
      { step: 'Escrow Payout Frozen Automatically', timestamp: '2026-08-01T10:05:00Z', completed: true },
      { step: 'Joint Sealed Sample Dispatched to NABL Re-test Lab', timestamp: '2026-08-02T14:30:00Z', completed: true },
      { step: 'Independent Chromatography & Moisture Audit', timestamp: '2026-08-04T09:00:00Z', completed: false },
      { step: 'Admin Settlement & Escrow Apportionment', timestamp: '2026-08-05T17:00:00Z', completed: false },
    ],
    createdAt: '2026-08-01T10:00:00Z',
  },
];

const SEED_AUDIT_LOGS = [
  {
    id: 'aud-101',
    actorId: 'usr_admin_01',
    actorRole: 'admin',
    action: 'APPROVE_ORGANIC_CERTIFICATE',
    targetType: 'CERTIFICATION',
    targetId: 'cert-1',
    reason: 'Verified against APEDA National Organic Registry license NPOP/NAB/0014/2025',
    timestamp: '2026-01-16T10:00:00Z',
  },
  {
    id: 'aud-102',
    actorId: 'system_escrow_engine',
    actorRole: 'escrow_service',
    action: 'FREEZE_ESCROW_ON_DISPUTE',
    targetType: 'ORDER',
    targetId: 'ORD-2026-8802',
    reason: 'Quality variance dispute disp-901 filed by buyer; funds held in escrow pool',
    timestamp: '2026-08-01T10:05:00Z',
  },
];

module.exports = {
  SEED_USERS,
  SEED_CERTIFICATIONS,
  SEED_PRODUCTS,
  SEED_COMMODITY_PRICES,
  SEED_ORDERS,
  SEED_SHIPMENTS,
  SEED_COMMUNITY_POSTS,
  SEED_AI_DIAGNOSES,
  SEED_DISPUTES,
  SEED_AUDIT_LOGS,
};
