/**
 * Eco Swadesh - Comprehensive Seed Dataset
 * Contains rich, production-grade initial mock entities across all 6 personas,
 * certified products, IoT heavy freight shipments, QR seals, AI knowledge base,
 * community posts, and audit logs.
 */

const SEED_USERS = [
  {
    id: 'usr_farmer_01',
    phoneNumber: '+919876543210',
    countryCode: 'IN',
    name: 'Ramesh Patel',
    email: 'ramesh.patel@ecoswadesh.com',
    persona: 'farmer',
    roles: ['farmer', 'seller'],
    verified: true,
    location: 'Indore, Madhya Pradesh, India',
    farmSizeAcres: 18,
    primaryCrops: ['Sharbati Wheat', 'Soybean', 'Basmati Rice'],
    certifications: ['NPOP/NAB/0014/2025', 'MH-AGRI-ORG-4402'],
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'usr_consumer_01',
    phoneNumber: '+919811122233',
    countryCode: 'IN',
    name: 'Pooja Sharma',
    email: 'pooja.sharma@gmail.com',
    persona: 'consumer',
    roles: ['consumer', 'gardener'],
    verified: true,
    location: 'Mumbai, Maharashtra, India',
    gardenType: 'Urban Balcony & Terrace Garden',
    createdAt: '2026-02-10T11:20:00Z',
  },
  {
    id: 'usr_bulk_01',
    phoneNumber: '+919822334455',
    countryCode: 'IN',
    name: 'AgroFlour Milling Mills Corp',
    contactPerson: 'Vikram Mehta',
    email: 'procurement@agroflour.com',
    persona: 'bulkBuyer',
    roles: ['bulkBuyer'],
    verified: true,
    location: 'Pune Industrial Area, Maharashtra, India',
    gstNumber: '27AABCA1234F1Z5',
    escrowDepositBalance: 1500000,
    createdAt: '2026-01-05T09:30:00Z',
  },
  {
    id: 'usr_seller_01',
    phoneNumber: '+919833445566',
    countryCode: 'IN',
    name: 'GreenBio Earth Labs Inc.',
    contactPerson: 'Dr. Suresh Joshi',
    email: 'sales@greenbioearth.com',
    persona: 'seller',
    roles: ['seller'],
    verified: true,
    location: 'Ahmedabad, Gujarat, India',
    licenseNo: 'NPOP/NAB/0014/2025',
    labPurityRating: 99.8,
    createdAt: '2025-11-20T14:15:00Z',
  },
  {
    id: 'usr_expert_01',
    phoneNumber: '+919844556677',
    countryCode: 'IN',
    name: 'Dr. Anita Deshmukh',
    email: 'dr.anita@soilmicrobio.org',
    persona: 'expert',
    roles: ['expert'],
    verified: true,
    title: 'Senior Agronomist & Soil Microbiologist (PhD, IARI)',
    specializations: ['Soil Health', 'Microbial Inoculants', 'Organic Transition', 'Pest Biocontrol'],
    consultationRateINR: 1200,
    rating: 4.95,
    consultationsCompleted: 84,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    createdAt: '2025-10-01T10:00:00Z',
  },
  {
    id: 'usr_admin_01',
    phoneNumber: '+919855667788',
    countryCode: 'IN',
    name: 'Swadesh Compliance Admin',
    email: 'compliance@ecoswadesh.com',
    persona: 'admin',
    roles: ['admin', 'moderator'],
    verified: true,
    department: 'Trust, Certification & Regulatory Affairs',
    createdAt: '2025-09-01T08:00:00Z',
  },
];

const SEED_CERTIFICATIONS = [
  {
    id: 'cert-1',
    name: 'Jaivik Bharat / NPOP Organic',
    type: 'NATIONAL',
    country: 'India',
    issuingAuthority: 'APEDA Ministry of Commerce & Industry',
    licenseNo: 'NPOP/NAB/0014/2025',
    verifiedScore: 99,
    validUntil: '2028-12-31',
    badgeText: 'National Organic Standard',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-2',
    name: 'USDA Organic NOP Certified',
    type: 'INTERNATIONAL',
    country: 'United States / Global',
    issuingAuthority: 'USDA National Organic Program',
    licenseNo: 'USDA-NOP-884920-US',
    verifiedScore: 98,
    validUntil: '2027-09-30',
    badgeText: 'USDA Global Organic Standard',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-3',
    name: 'Maharashtra State Organic Board Seal',
    type: 'LOCAL_GOV',
    country: 'India (Maharashtra State)',
    issuingAuthority: 'State Department of Agriculture & Agro-Board',
    licenseNo: 'MH-AGRI-ORG-4402',
    verifiedScore: 96,
    validUntil: '2026-11-15',
    badgeText: 'Local Govt Approved',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'cert-4',
    name: 'CCOF Local Regional Authority Seal',
    type: 'LOCAL_GOV',
    country: 'United States (California)',
    issuingAuthority: 'California Dept of Food & Agriculture (CDFA)',
    licenseNo: 'CDFA-CCOF-77189-CA',
    verifiedScore: 97,
    validUntil: '2027-04-20',
    badgeText: 'Local State Approved',
    status: 'ACTIVE',
    logo: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=100&auto=format&fit=crop&q=80',
  },
];

const SEED_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Bio-Active NPK Liquid Organic Fertilizer',
    category: 'fertilizers',
    sellerId: 'usr_seller_01',
    sellerName: 'GreenBio Earth Labs Inc.',
    sellerType: 'Fertilizer Manufacturer',
    origin: 'Gujarat, India',
    rating: 4.9,
    reviewsCount: 142,
    certifiedType: 'NATIONAL',
    certName: 'Jaivik Bharat & USDA Organic',
    certLicense: 'NPOP/NAB/0014/2025',
    labPurityRating: '99.4% Chemical-Free',
    image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?w=600&auto=format&fit=crop&q=80',
    retailPrice: 450,
    retailUnit: 'Liter',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 85000,
    bulkMinTons: 2,
    bulkUnit: 'Ton',
    description: 'High-potency microbial nitrogen, phosphorus, and potassium liquid fertilizer. Enhances root mass by 40% and boosts soil organic carbon naturally.',
    npkRatio: 'N: 6% | P: 4% | K: 8%',
    usageDose: '5 ml per liter of irrigation water or 200 Liters per acre via drip.',
    inStock: true,
    stockQuantity: 4500,
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Direct Farm Harvest: 100% Organic Sharbati Wheat',
    category: 'bulkHarvest',
    sellerId: 'usr_farmer_01',
    sellerName: 'Swadesh Agro-Cooperative Farmer Collective',
    sellerType: 'Certified Organic Farmer Collective',
    origin: 'Madhya Pradesh, India',
    rating: 4.95,
    reviewsCount: 88,
    certifiedType: 'LOCAL_GOV',
    certName: 'MP State Agro Organic Board & Jaivik Bharat',
    certLicense: 'MH-AGRI-ORG-4402',
    labPurityRating: '100% Pesticide-Residue Free',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80',
    retailPrice: 65,
    retailUnit: 'Kg',
    retailMinQty: 5,
    bulkAvailable: true,
    bulkPricePerTon: 42000,
    bulkMinTons: 5,
    bulkUnit: 'Ton',
    description: 'Premium golden Sharbati wheat grown without synthetic pesticides or chemical fertilizers. Direct farm shipment to flour mills, food processors, and bulk buyers.',
    moistureContent: '11.5% Max',
    grainPurity: '99.8%',
    inStock: true,
    stockQuantity: 120, // 120 Tons
    createdAt: '2026-01-22T08:30:00Z',
  },
  {
    id: 'prod-3',
    name: 'Neem-Shield Bio-Pesticide & Cold-Pressed Neem Oil',
    category: 'bioPesticides',
    sellerId: 'usr_seller_01',
    sellerName: 'NeemTech Organics Ltd.',
    sellerType: 'Bio-Input Manufacturer',
    origin: 'Rajasthan, India',
    rating: 4.8,
    reviewsCount: 96,
    certifiedType: 'NATIONAL',
    certName: 'USDA NOP & EU Bio Standards',
    certLicense: 'USDA-NOP-884920-US',
    labPurityRating: '10,000 PPM Azadirachtin',
    image: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=600&auto=format&fit=crop&q=80',
    retailPrice: 380,
    retailUnit: '500ml Bottle',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 110000,
    bulkMinTons: 1,
    bulkUnit: 'Ton (Barrel Pack)',
    description: 'Broad-spectrum botanical pesticide effective against caterpillars, aphids, thrips, and whiteflies. Safe for beneficial pollinators like bees.',
    inStock: true,
    stockQuantity: 1800,
    createdAt: '2026-02-01T12:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Premium Vermicompost Soil Conditioner (Enriched with Humic Acid)',
    category: 'fertilizers',
    sellerId: 'usr_farmer_01',
    sellerName: 'EarthWorm Gold Farmers Union',
    sellerType: 'Local Farmer Cooperative',
    origin: 'Punjab, India',
    rating: 4.7,
    reviewsCount: 210,
    certifiedType: 'LOCAL_GOV',
    certName: 'Punjab State Organic Agriculture Council',
    certLicense: 'PB-AGRI-ORG-1029',
    labPurityRating: '100% Pure Worm Castings',
    image: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?w=600&auto=format&fit=crop&q=80',
    retailPrice: 25,
    retailUnit: 'Kg Bag',
    retailMinQty: 5,
    bulkAvailable: true,
    bulkPricePerTon: 12500,
    bulkMinTons: 3,
    bulkUnit: 'Ton',
    description: 'Rich dark humus created by Eisenia Fetida earthworms. Loaded with beneficial mycorrhizae, micronutrients, and humic substances for soil rejuvenation.',
    inStock: true,
    stockQuantity: 80, // Tons
    createdAt: '2026-02-05T14:40:00Z',
  },
  {
    id: 'prod-5',
    name: 'High-Yield Hybrid Organic Tomato Seeds (F1 Disease Resistant)',
    category: 'seeds',
    sellerId: 'usr_seller_01',
    sellerName: 'Vedic Seed Innovations',
    sellerType: 'Seed Nursery & Breeder',
    origin: 'Karnataka, India',
    rating: 4.9,
    reviewsCount: 175,
    certifiedType: 'NATIONAL',
    certName: 'National Seed Certification Board',
    certLicense: 'NSCB-IND-99120',
    labPurityRating: '98% Germination Guaranteed',
    image: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&auto=format&fit=crop&q=80',
    retailPrice: 220,
    retailUnit: '10g Packet',
    retailMinQty: 1,
    bulkAvailable: false,
    description: 'High-yielding semi-determinate tomato seeds bred for wilt resistance and intense flavor. Suitable for open field and greenhouse cultivation.',
    inStock: true,
    stockQuantity: 500,
    createdAt: '2026-02-12T09:10:00Z',
  },
  {
    id: 'prod-6',
    name: 'Solar-Powered Automated Drip Irrigation Kit (1 Acre)',
    category: 'equipment',
    sellerId: 'usr_seller_01',
    sellerName: 'SunAgro Tech Systems',
    sellerType: 'Equipment Supplier',
    origin: 'Maharashtra, India',
    rating: 4.85,
    reviewsCount: 54,
    certifiedType: 'NATIONAL',
    certName: 'Bureau of Indian Standards (BIS Certified)',
    certLicense: 'BIS-AGRI-44120',
    labPurityRating: 'ISO 9001:2025 Quality Passed',
    image: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=600&auto=format&fit=crop&q=80',
    retailPrice: 24500,
    retailUnit: 'Full Kit (1 Acre)',
    retailMinQty: 1,
    bulkAvailable: true,
    bulkPricePerTon: 215000,
    bulkMinTons: 1,
    bulkUnit: 'Set of 10 Acres',
    description: 'Complete water-saving precision drip irrigation system with automatic solar timer pump. Reduces water usage by up to 60%.',
    inStock: true,
    stockQuantity: 40,
    createdAt: '2026-02-15T16:20:00Z',
  },
];

const SEED_COMMODITY_PRICES = [
  { crop: 'Organic Wheat (MP Sharbati)', priceRetail: '₹65 / Kg', priceBulk: '₹42,000 / Ton', change: '+2.4%', trend: 'up' },
  { crop: 'Bio-NPK Liquid Fertilizer', priceRetail: '₹450 / Liter', priceBulk: '₹85,000 / Ton', change: '-0.8%', trend: 'down' },
  { crop: 'Organic Basmati Paddy Rice', priceRetail: '₹95 / Kg', priceBulk: '₹72,000 / Ton', change: '+3.1%', trend: 'up' },
  { crop: 'Cold-Pressed Neem Oil', priceRetail: '₹380 / 500ml', priceBulk: '₹110,000 / Ton', change: '0.0%', trend: 'stable' },
  { crop: 'Organic Vermicompost', priceRetail: '₹25 / Kg', priceBulk: '₹12,500 / Ton', change: '+1.5%', trend: 'up' },
];

const SEED_ORDERS = [
  {
    id: 'ORD-2026-9041',
    buyerId: 'usr_bulk_01',
    buyerName: 'AgroFlour Milling Mills Corp',
    sellerId: 'usr_farmer_01',
    sellerName: 'Swadesh Agro-Cooperative Farmer Collective',
    logisticsType: 'HEAVY_FREIGHT',
    shippingAddress: 'Central Warehouse, Plot 14, Pune Industrial Area, Maharashtra, IN',
    currency: 'INR',
    items: [
      {
        productId: 'prod-2',
        productName: 'Direct Farm Harvest: 100% Organic Sharbati Wheat',
        isBulk: true,
        quantity: 10,
        unit: 'Ton',
        unitPrice: 42000,
        total: 420000,
        certificationSnapshot: {
          certName: 'MP State Agro Organic Board & Jaivik Bharat',
          certLicense: 'MH-AGRI-ORG-4402',
          verifiedScore: 96,
        },
      },
    ],
    subtotal: 420000,
    freightCharges: 4500,
    platformFeePct: 0.5,
    platformFee: 2100,
    grandTotal: 426600,
    escrowContractId: 'ESC-9041',
    escrowStatus: 'HELD_IN_ESCROW_POOL',
    paymentStatus: 'PAID_TO_ESCROW',
    paymentMethod: 'RAZORPAY_ROUTE_ESCROW',
    destinationLabInspectionStatus: 'PENDING_ARRIVAL',
    createdAt: '2026-07-24T06:30:00Z',
    shipmentId: 'SHIP-8921',
  },
  {
    id: 'ORD-2026-4402',
    buyerId: 'usr_consumer_01',
    buyerName: 'Pooja Sharma',
    sellerId: 'usr_seller_01',
    sellerName: 'GreenBio Earth Labs Inc.',
    logisticsType: 'RETAIL_PARCEL',
    shippingAddress: 'Flat 402, Sunshine Heights, Bandra West, Mumbai, IN',
    currency: 'INR',
    items: [
      {
        productId: 'prod-1',
        productName: 'Bio-Active NPK Liquid Organic Fertilizer',
        isBulk: false,
        quantity: 2,
        unit: 'Liter',
        unitPrice: 450,
        total: 900,
        certificationSnapshot: {
          certName: 'Jaivik Bharat & USDA Organic',
          certLicense: 'NPOP/NAB/0014/2025',
          verifiedScore: 99,
        },
      },
    ],
    subtotal: 900,
    freightCharges: 60,
    platformFee: 0,
    grandTotal: 960,
    escrowContractId: 'ESC-4402',
    escrowStatus: 'RELEASED_TO_SELLER',
    paymentStatus: 'PAID_SETTLED',
    paymentMethod: 'UPI_DIRECT',
    createdAt: '2026-07-23T14:15:00Z',
    shipmentId: 'SHIP-4402',
  },
];

const SEED_SHIPMENTS = [
  {
    id: 'SHIP-8921',
    orderId: 'ORD-2026-9041',
    type: 'BULK_FREIGHT',
    title: '15 Tons Organic Sharbati Wheat Truckload',
    origin: 'Farm #4, Indore, MP',
    destination: 'AgroProcessor Flour Mill Warehouse, Pune, MH',
    weight: '15.0 Tons',
    carrier: 'EcoFreight Heavy Trucking Direct',
    status: 'IN_TRANSIT',
    driverName: 'Ramesh Singh',
    driverPhone: '+91 98230 11200',
    vehicleNo: 'MH-12-VT-9921',
    estDelivery: 'Tomorrow, 04:30 PM',
    escrowStatus: '₹6,30,000 Held in Escrow (Release after destination lab check)',
    telemetry: {
      temperatureCelsius: 24.2,
      humidityPct: 58.0,
      cargoMoisturePct: 11.2,
      gpsLatitude: 19.8762,
      gpsLongitude: 75.3433,
      speedKmh: 54,
      lastUpdated: new Date().toISOString(),
    },
    milestones: [
      { label: 'Harvest Loaded at Farm', date: '24 Jul, 08:00 AM', completed: true, timestamp: '2026-07-24T08:00:00Z' },
      { label: 'Weighbridge & Initial Quality Stamp', date: '24 Jul, 11:30 AM', completed: true, timestamp: '2026-07-24T11:30:00Z' },
      { label: 'En-Route on Highway NH-52', date: '24 Jul, 04:00 PM', completed: true, timestamp: '2026-07-24T16:00:00Z' },
      { label: 'Destination Lab Check at Warehouse', date: '25 Jul, 02:00 PM', completed: false },
      { label: 'Final Escrow Release to Farmer', date: '25 Jul, 05:00 PM', completed: false },
    ],
  },
  {
    id: 'SHIP-4402',
    orderId: 'ORD-2026-4402',
    type: 'RETAIL_PARCEL',
    title: '5 Liters Bio-NPK Liquid & 2 Kg Neem Powder',
    origin: 'GreenBio Earth Depot, Ahmedabad, GJ',
    destination: 'Green Acres Home Farm, Jaipur, RJ',
    weight: '7.2 Kg',
    carrier: 'GreenParcel Carbon-Neutral Courier',
    status: 'DISPATCHED',
    trackingNo: 'GP-992018442-IN',
    estDelivery: '26 Jul, 02:00 PM',
    escrowStatus: 'Payment Completed via UPI',
    telemetry: {
      temperatureCelsius: 22.0,
      humidityPct: 50.0,
      lastUpdated: new Date().toISOString(),
    },
    milestones: [
      { label: 'Order Confirmed', date: '23 Jul, 02:15 PM', completed: true },
      { label: 'Lab Sealed & Packaged', date: '24 Jul, 09:00 AM', completed: true },
      { label: 'Dispatched via GreenParcel Express', date: '24 Jul, 01:00 PM', completed: true },
      { label: 'Out for Last-Mile Delivery', date: '26 Jul, 09:00 AM', completed: false },
    ],
  },
];

const SEED_COMMUNITY_POSTS = [
  {
    id: 'post-1',
    author: 'Dr. Anita Deshmukh',
    role: 'EXPERT',
    verifiedExpert: true,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    title: 'How to transition 5 acres from chemical farming to 100% Certified Organic without yield drop',
    content: 'Transitioning requires a 3-phase soil rejuvenation strategy. Start with bio-char and vermicompost to reseed beneficial mycorrhizae bacteria before cutting synthetic nitrogen. Within 120 days, soil organic carbon rises by 0.4% which stabilizes yields.',
    tags: ['Soil Health', 'Organic Transition', 'Bio-Fertilizers'],
    upvotes: 246,
    repliesCount: 38,
    date: '2 hours ago',
    createdAt: '2026-08-08T12:00:00Z',
  },
  {
    id: 'post-2',
    author: 'Gurpreet Singh',
    role: 'FARMER',
    verifiedExpert: false,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    title: 'Direct Bulk Sales Experience: Bypassing Mandi Middlemen for 18 Tons of Wheat',
    content: 'Used Eco Swadesh Direct Freight last week to supply 18 Tons of organic wheat directly to a Pune flour mill. Escrow payment was released within 2 hours of lab test at warehouse! Received ₹42,000/Ton instead of ₹31,000 at local mandi.',
    tags: ['Direct Bulk Trade', 'Zero Middlemen', 'Escrow Payment'],
    upvotes: 189,
    repliesCount: 24,
    date: '5 hours ago',
    createdAt: '2026-08-08T09:30:00Z',
  },
];

const SEED_AI_DIAGNOSES = [
  {
    id: 'diag-1',
    cropName: 'Tomato Plant (Solanum lycopersicum)',
    detectedDisease: 'Early Bacterial Leaf Blight (Alternaria solani)',
    confidence: '96.8% Accuracy',
    confidenceScore: 0.968,
    severity: 'Moderate Infection',
    organicRecipes: [
      'Spray 5ml/L Cold-Pressed Neem Oil (10,000 PPM) with 2g/L Baking Soda solution every 5 days.',
      'Apply Trichoderma viride bio-fungicide during early morning hours to colonize leaf surface.',
      'Prune lower infected yellow leaves and burn them away from field to prevent airborne spore propagation.',
    ],
    recommendedFertilizer: 'Bio-Active Potassium & Seaweed Extract for natural plant systemic resistance.',
  },
  {
    id: 'diag-2',
    cropName: 'Cotton (Gossypium)',
    detectedDisease: 'Bacterial Blight & Whitefly Nymph Cluster',
    confidence: '94.2% Accuracy',
    confidenceScore: 0.942,
    severity: 'Early Warning',
    organicRecipes: [
      'Apply 5% Neem Seed Kernel Extract (NSKE) spray at sunset.',
      'Install 15 yellow sticky traps per acre at crop canopy height.',
      'Release Chrysoperla carnea green lacewing predatory larvae for biological whitefly control.',
    ],
    recommendedFertilizer: 'Bio-NPK Liquid foliar spray at 4ml/Liter water.',
  },
];

const SEED_DISPUTES = [
  {
    id: 'disp-901',
    orderId: 'ORD-2026-8802',
    buyerId: 'usr_bulk_01',
    sellerId: 'usr_farmer_01',
    productName: 'Organic Basmati Paddy Rice 20 Tons',
    claimType: 'Moisture Level Exceeds Contract Specification (14.2% vs 12.0% Max)',
    disputeAmountINR: 1440000,
    escrowStatus: 'FROZEN_PENDING_RETEST',
    independentLab: 'NABL Accredited AgriQuality Lab, Indore',
    sampleBatchId: 'BATCH-2026-NPOP-4421',
    status: 'SAMPLE_IN_TRANSIT_TO_LAB',
    timeline: [
      { step: 'Buyer Lodged Dispute at Destination Lab', timestamp: '2026-08-01T10:00:00Z', completed: true },
      { step: 'Escrow Payout Frozen Automatically', timestamp: '2026-08-01T10:05:00Z', completed: true },
      { step: 'Joint Sealed Sample Dispatched to NABL Re-test Lab', timestamp: '2026-08-02T14:30:00Z', completed: true },
      { step: 'Independent Chromatography & Moisture Audit', timestamp: '2026-08-04T09:00:00Z', completed: false },
      { step: 'Admin Settlement & Escrow Apportionment', timestamp: '2026-08-05T17:00:00Z', completed: false },
    ],
    createdAt: '2026-08-01T10:00:00Z',
  },
];

const SEED_AUDIT_LOGS = [
  {
    id: 'aud-101',
    actorId: 'usr_admin_01',
    actorRole: 'admin',
    action: 'APPROVE_ORGANIC_CERTIFICATE',
    targetType: 'CERTIFICATION',
    targetId: 'cert-1',
    reason: 'Verified against APEDA National Organic Registry license NPOP/NAB/0014/2025',
    timestamp: '2026-01-16T10:00:00Z',
  },
  {
    id: 'aud-102',
    actorId: 'system_escrow_engine',
    actorRole: 'escrow_service',
    action: 'FREEZE_ESCROW_ON_DISPUTE',
    targetType: 'ORDER',
    targetId: 'ORD-2026-8802',
    reason: 'Quality variance dispute disp-901 filed by buyer; funds held in escrow pool',
    timestamp: '2026-08-01T10:05:00Z',
  },
];

module.exports = {
  SEED_USERS,
  SEED_CERTIFICATIONS,
  SEED_PRODUCTS,
  SEED_COMMODITY_PRICES,
  SEED_ORDERS,
  SEED_SHIPMENTS,
  SEED_COMMUNITY_POSTS,
  SEED_AI_DIAGNOSES,
  SEED_DISPUTES,
  SEED_AUDIT_LOGS,
};
